package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// dockerFrom matches FROM lines, skipping any --flag options (e.g.
	// --platform=$BUILDPLATFORM) before the image name. Captures the image
	// and the optional AS alias.
	dockerFrom = regexp.MustCompile(`(?i)^FROM\s+(?:--[a-zA-Z][^\s]*\s+)*(\S+)(?:\s+AS\s+(\S+))?`)
	// dockerInstruction matches the instruction keyword at the start of a line.
	dockerInstruction = regexp.MustCompile(`(?i)^(RUN|COPY|ADD|WORKDIR|ENV|ARG|EXPOSE|ENTRYPOINT|CMD|LABEL|USER|VOLUME|HEALTHCHECK|ONBUILD|STOPSIGNAL|SHELL)\s`)
	// dockerComment is a Dockerfile comment line.
	dockerComment = regexp.MustCompile(`^\s*#`)
	// dockerGenerated marks generated Dockerfiles.
	dockerGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|autogenerated`)
)

// dockerfileStage tracks one FROM block while parsing.
type dockerfileStage struct {
	image     string
	alias     string
	startLine int
	endLine   int
	verbs     []string // distinct instruction verbs, insertion order
	verbSeen  map[string]bool
}

// parseDockerfile builds a FileMap from a Dockerfile. Each FROM instruction
// starts a new stage; the stage entry spans from its FROM line to the last
// line before the next FROM (or the end of file). The Kind label lists the
// base image, the optional stage name, and up to four distinct instruction
// verbs used in that stage.
func parseDockerfile(src, _ string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasDockerfileStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no FROM instruction found")
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if dockerGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	var stages []*dockerfileStage
	var cur *dockerfileStage

	closeStage := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			stages = append(stages, cur)
		}
	}

	for i, raw := range lines {
		lineNo := i + 1

		trimmed := strings.TrimSpace(raw)
		if trimmed == "" || dockerComment.MatchString(raw) {
			continue
		}

		if m := dockerFrom.FindStringSubmatch(trimmed); m != nil {
			closeStage(lineNo - 1)
			cur = &dockerfileStage{
				image:     m[1],
				alias:     m[2],
				startLine: lineNo,
				verbSeen:  map[string]bool{},
			}
			continue
		}

		if cur == nil {
			continue
		}

		if m := dockerInstruction.FindStringSubmatch(trimmed); m != nil {
			verb := strings.ToUpper(m[1])
			if !cur.verbSeen[verb] && len(cur.verbs) < 4 {
				cur.verbs = append(cur.verbs, verb)
				cur.verbSeen[verb] = true
			}
		}
	}
	closeStage(len(lines))

	if len(stages) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: no stages found")
	}

	var entries []digest.MapEntry
	var symbols []string

	for _, s := range stages {
		label := dockerStageLabel(s)
		if len(symbols) < 40 {
			symbols = append(symbols, label)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(s.startLine, s.endLine),
			Kind:  label,
		})
	}

	stageWord := "stage"
	if len(stages) != 1 {
		stageWord = "stages"
	}
	summary := fmt.Sprintf("Dockerfile — %d %s", len(stages), stageWord)
	if generated {
		summary += " — generated, do not edit directly"
	}

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
	}, nil
}

// dockerStageLabel builds the Kind/symbol label for one stage.
func dockerStageLabel(s *dockerfileStage) string {
	// Shorten well-known base images for readability.
	image := s.image
	if colon := strings.LastIndexByte(image, ':'); colon > 0 {
		// "node:18-alpine" → "node:18-alpine" (keep full tag; it's meaningful)
	}

	label := "FROM " + image
	if s.alias != "" {
		label += " AS " + s.alias
	}
	if len(s.verbs) > 0 {
		label += " — " + strings.Join(s.verbs, ", ")
	}
	return label
}

// hasDockerfileStructure returns true when at least one FROM instruction is present.
func hasDockerfileStructure(lines []string) bool {
	for _, l := range lines {
		if dockerFrom.MatchString(strings.TrimSpace(l)) {
			return true
		}
	}
	return false
}
