package filemap_test

import (
	"strings"
	"testing"

	"github.com/kaushal/skim/internal/filemap"
)

const simpleGoFile = `// Package auth provides JWT-based authentication helpers.
package auth

import (
	"errors"
	"time"
)

// ErrExpired is returned when a token has passed its expiry time.
var ErrExpired = errors.New("token expired")

// Token holds the parsed contents of a JWT.
type Token struct {
	Subject  string
	Expiry   time.Time
	IsAdmin  bool
}

// Parse decodes and validates a JWT string.
func Parse(raw string) (Token, error) {
	if raw == "" {
		return Token{}, ErrExpired
	}
	return Token{Subject: "user"}, nil
}

// Validate checks whether t has not expired.
func (t Token) Validate() error {
	if time.Now().After(t.Expiry) {
		return ErrExpired
	}
	return nil
}
`

func TestGenerate_GoFile_ReturnsFalseForTestFile(t *testing.T) {
	_, ok := filemap.Generate(simpleGoFile, "internal/auth/auth_test.go")
	if ok {
		t.Error("should not generate map for _test.go files")
	}
}

func TestGenerate_GoFile_ReturnsFalseForUnsupportedExt(t *testing.T) {
	// .rb is not a supported extension — must fall through to the worker.
	_, ok := filemap.Generate(simpleGoFile, "auth.rb")
	if ok {
		t.Error("should return false for unsupported extension (.rb)")
	}
}

func TestGenerate_GoFile_ReturnsFalseForInvalidContent(t *testing.T) {
	_, ok := filemap.Generate(strings.Repeat("x\n", 100), "big.go")
	if ok {
		t.Error("should return false for content without package declaration")
	}
}

func TestGenerate_GoFile_SummaryFromDocComment(t *testing.T) {
	fm, ok := filemap.Generate(simpleGoFile, "internal/auth/auth.go")
	if !ok {
		t.Fatal("expected ok=true for valid Go file")
	}
	if !strings.Contains(fm.Summary, "auth") {
		t.Errorf("summary %q should mention package name", fm.Summary)
	}
	if fm.Summary == "" {
		t.Error("summary must not be empty")
	}
}

func TestGenerate_GoFile_MapNonEmpty(t *testing.T) {
	fm, ok := filemap.Generate(simpleGoFile, "auth.go")
	if !ok {
		t.Fatal("expected ok")
	}
	if len(fm.Map) == 0 {
		t.Error("map must not be empty")
	}
}

func TestGenerate_GoFile_HasExportedSymbols(t *testing.T) {
	fm, ok := filemap.Generate(simpleGoFile, "auth.go")
	if !ok {
		t.Fatal("expected ok")
	}
	syms := strings.Join(fm.Symbols, ",")
	if !strings.Contains(syms, "ErrExpired") {
		t.Errorf("symbols %q should contain ErrExpired", syms)
	}
	if !strings.Contains(syms, "Token") {
		t.Errorf("symbols %q should contain Token", syms)
	}
	if !strings.Contains(syms, "Parse") {
		t.Errorf("symbols %q should contain Parse", syms)
	}
}

func TestGenerate_GoFile_MapContainsFuncEntry(t *testing.T) {
	fm, ok := filemap.Generate(simpleGoFile, "auth.go")
	if !ok {
		t.Fatal("expected ok")
	}
	var hasParse bool
	for _, entry := range fm.Map {
		if strings.Contains(entry.Kind, "func Parse") {
			hasParse = true
		}
	}
	if !hasParse {
		t.Errorf("map entries should include func Parse; got: %v", fm.Map)
	}
}

func TestGenerate_GoFile_MapContainsImports(t *testing.T) {
	fm, ok := filemap.Generate(simpleGoFile, "auth.go")
	if !ok {
		t.Fatal("expected ok")
	}
	var hasImports bool
	for _, entry := range fm.Map {
		if strings.Contains(entry.Kind, "imports") {
			hasImports = true
		}
	}
	if !hasImports {
		t.Errorf("map entries should include an imports block; got: %v", fm.Map)
	}
}

func TestGenerate_GoFile_LineRangesValid(t *testing.T) {
	fm, ok := filemap.Generate(simpleGoFile, "auth.go")
	if !ok {
		t.Fatal("expected ok")
	}
	for _, entry := range fm.Map {
		if entry.Lines == "" {
			t.Errorf("entry %q has empty Lines", entry.Kind)
		}
	}
}

func TestGenerate_GoFile_SyntaxErrorsYieldPartialMap(t *testing.T) {
	// A file with a valid package declaration but a syntax error in a function
	// body should still produce a useful map via partial parse.
	partial := `package broken

func Good() string { return "ok" }

func Bad(  // missing closing paren
`
	fm, ok := filemap.Generate(partial, "broken.go")
	if !ok {
		t.Fatal("partial parse should still yield a map")
	}
	if len(fm.Map) == 0 {
		t.Error("partial map must not be empty")
	}
	// Good function should appear
	var hasGood bool
	for _, e := range fm.Map {
		if strings.Contains(e.Kind, "Good") {
			hasGood = true
		}
	}
	if !hasGood {
		t.Errorf("Good() should appear in partial map; entries: %v", fm.Map)
	}
}

func TestGenerate_GoFile_GeneratedFileNoted(t *testing.T) {
	gen := `// Code generated by protoc-gen-go. DO NOT EDIT.
package pb

type Foo struct{}
`
	fm, ok := filemap.Generate(gen, "foo.pb.go")
	if !ok {
		t.Fatal("expected ok for generated file")
	}
	if !strings.Contains(fm.Notes, "generated") {
		t.Errorf("notes %q should mention generated file", fm.Notes)
	}
}

func TestGenerate_GoFile_NoSymbolsDuplication(t *testing.T) {
	// A type with a method should list the type name once, not twice.
	src := `package foo

type Foo struct{}
func (f Foo) Bar() {}
func (f Foo) Baz() {}
`
	fm, ok := filemap.Generate(src, "foo.go")
	if !ok {
		t.Fatal("expected ok")
	}
	seen := map[string]int{}
	for _, s := range fm.Symbols {
		seen[s]++
	}
	for sym, n := range seen {
		if n > 1 {
			t.Errorf("symbol %q appears %d times, expected once", sym, n)
		}
	}
}
