package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// hclBlock matches a top-level HCL block opener:
	//   resource "aws_s3_bucket" "main" {
	//   variable "region" {
	//   terraform {
	// Groups: (1) block type, (2) first label (or ""), (3) second label (or "")
	hclBlock = regexp.MustCompile(
		`^([a-zA-Z][a-zA-Z0-9_]*)` +
			`(?:\s+"([^"]*)")?` +
			`(?:\s+"([^"]*)")?` +
			`\s*\{`,
	)
	// hclComment matches single-line HCL comments (# or //).
	hclComment     = regexp.MustCompile(`^\s*(?:#|//)`)
	hclBlockComment = regexp.MustCompile(`^\s*/\*`)
	// hclGenerated marks generated Terraform files.
	hclGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|autogenerated|This file is maintained automatically`)
)

// hclTopLevelTypes is the set of block types that are structurally interesting
// at the top level. Inner blocks (e.g. lifecycle, connection, provisioner) are
// skipped.
var hclTopLevelTypes = map[string]bool{
	"resource": true, "data": true, "variable": true, "output": true,
	"module": true, "provider": true, "terraform": true, "locals": true,
	"moved": true, "import": true, "check": true,
}

// hclLockFileNames are HCL files that must never be parsed — they contain
// exact provider version pins required for reproducible runs.
var hclLockFileNames = map[string]bool{
	".terraform.lock.hcl": true,
}

// hclBlock tracks one top-level HCL block while parsing.
type hclTopBlock struct {
	kind      string // resource, data, variable, …
	label1    string // first quoted label (resource type, module name, …)
	label2    string // second quoted label (resource name); empty for most block types
	startLine int
	endLine   int
}

// parseHCLFile builds a FileMap from an HCL or Terraform file. Each top-level
// block becomes one map entry. The Kind label follows Terraform conventions:
//
//	resource "aws_s3_bucket" "main"   → resource aws_s3_bucket.main
//	variable "region"                 → variable region
//	terraform                         → terraform
func parseHCLFile(src, filePath string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasHCLStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no HCL block structure found")
	}

	generated := false
	for _, l := range lines[:min(len(lines), 8)] {
		if hclGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	var blocks []*hclTopBlock
	var cur *hclTopBlock
	depth := 0 // brace depth

	closeBlock := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			blocks = append(blocks, cur)
			cur = nil
		}
	}

	inBlockComment := false

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" {
			continue
		}

		// Block comment tracking.
		if inBlockComment {
			if strings.Contains(raw, "*/") {
				inBlockComment = false
			}
			continue
		}
		if hclBlockComment.MatchString(raw) {
			if !strings.Contains(raw, "*/") {
				inBlockComment = true
			}
			continue
		}
		if hclComment.MatchString(raw) {
			continue
		}

		// Count braces to track nesting depth.
		if cur != nil {
			for _, ch := range trimmed {
				if ch == '{' {
					depth++
				} else if ch == '}' {
					depth--
				}
			}
			if depth <= 0 {
				closeBlock(lineNo)
				depth = 0
			}
			continue
		}

		// Looking for a new top-level block.
		if m := hclBlock.FindStringSubmatch(trimmed); m != nil {
			blockType := m[1]
			if !hclTopLevelTypes[blockType] {
				continue
			}
			cur = &hclTopBlock{
				kind:      blockType,
				label1:    m[2],
				label2:    m[3],
				startLine: lineNo,
			}
			depth = 1 // the opening brace on this line
		}
	}
	closeBlock(len(lines))

	if len(blocks) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: no HCL blocks found")
	}

	var entries []digest.MapEntry
	var symbols []string

	for _, b := range blocks {
		label := hclBlockLabel(b)
		if len(symbols) < 40 {
			symbols = append(symbols, label)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(b.startLine, b.endLine),
			Kind:  label,
		})
	}

	summary := hclSummary(filePath, blocks, generated)

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
	}, nil
}

// hclBlockLabel builds the display label for one HCL block.
func hclBlockLabel(b *hclTopBlock) string {
	switch b.kind {
	case "resource", "data":
		if b.label1 != "" && b.label2 != "" {
			return b.kind + " " + b.label1 + "." + b.label2
		}
		if b.label1 != "" {
			return b.kind + " " + b.label1
		}
	case "variable", "output", "module", "provider":
		if b.label1 != "" {
			return b.kind + " " + b.label1
		}
	case "moved", "import", "check":
		if b.label1 != "" {
			return b.kind + " " + b.label1
		}
	}
	return b.kind
}

// hclSummary builds the top-level summary line.
func hclSummary(filePath string, blocks []*hclTopBlock, generated bool) string {
	// Count by type for a concise summary.
	counts := map[string]int{}
	for _, b := range blocks {
		counts[b.kind]++
	}

	// Order the interesting types for a readable summary.
	ordered := []string{"resource", "data", "module", "variable", "output", "provider", "terraform", "locals"}
	var parts []string
	for _, t := range ordered {
		if n := counts[t]; n > 0 {
			if n == 1 {
				parts = append(parts, fmt.Sprintf("1 %s", t))
			} else {
				parts = append(parts, fmt.Sprintf("%d %ss", n, t))
			}
		}
	}

	base := hclFileKind(filePath)
	summary := base + " — " + strings.Join(parts, ", ")
	if generated {
		summary += " — generated, do not edit directly"
	}
	return summary
}

// hclFileKind infers a human-readable file kind from the extension/name.
func hclFileKind(filePath string) string {
	lower := strings.ToLower(filePath)
	switch {
	case strings.HasSuffix(lower, ".tfvars"):
		return "Terraform variables"
	case strings.HasSuffix(lower, ".tf"):
		return "Terraform"
	default:
		return "HCL"
	}
}

// hasHCLStructure returns true when at least one recognized top-level block is
// present.
func hasHCLStructure(lines []string) bool {
	for _, l := range lines {
		if m := hclBlock.FindStringSubmatch(strings.TrimSpace(l)); m != nil {
			if hclTopLevelTypes[m[1]] {
				return true
			}
		}
	}
	return false
}
