package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// javaTopBlock matches a top-level type declaration.
	// Only type-shaping modifiers (abstract/final/sealed/…) land in group 1
	// so the label reads "abstract class Foo", not "public abstract class Foo".
	// Groups: (1) kind phrase, (2) name
	javaTopBlock = regexp.MustCompile(
		`^\s*(?:(?:public|private|protected|strictfp)\s+)*` +
			`((?:(?:abstract|final|sealed|non-sealed|static)\s+)*` +
			`(?:class|interface|enum|record|@interface))\s+([A-Za-z_][A-Za-z0-9_]*)`)
	// javaMethod matches a method declaration: modifiers + return type + name + "(".
	// The return-type group uses a broad match; the critical distinguisher
	// from field declarations is the trailing "(". Groups: (1) name
	javaMethod = regexp.MustCompile(
		`^\s*(?:(?:@\w+\s+)*)` + // inline annotations (@NonNull etc.)
			`(?:(?:public|private|protected|abstract|static|final|synchronized|native|default|transient|volatile)\s+)*` +
			`(?:<[^>]*>\s+)?` + // optional leading type parameters
			`[A-Za-z_@][\w.<>[\]?,\s]*\s+` + // return type (broad)
			`([A-Za-z_][A-Za-z0-9_]*)\s*\(`) // method name + "("
	// javaAnnotation matches a standalone annotation line.
	javaAnnotation = regexp.MustCompile(`^\s*@[A-Za-z_]`)
	// javaComment matches Java single-line comments.
	javaComment = regexp.MustCompile(`^\s*//`)
	// javaBlockComment matches the start of a /* ... */ comment.
	javaBlockComment = regexp.MustCompile(`^\s*/\*`)
	// javaGenerated detects generated Java files.
	javaGenerated = regexp.MustCompile(`@Generated|@generated|DO NOT EDIT|auto.?generated|This file was automatically generated|Generated by`)
	// javaStaticInit matches static initializer blocks ("static {").
	javaStaticInit = regexp.MustCompile(`^\s*static\s*\{`)
)

// javaBlock tracks one top-level Java type declaration while parsing.
type javaBlock struct {
	kind      string
	name      string
	startLine int
	endLine   int
	methods   []string
}

// parseJavaFile builds a FileMap from a Java source file. Each top-level type
// declaration becomes one map entry; its Kind label lists methods (up to 4,
// with +N overflow).
func parseJavaFile(src, _ string) (digest.FileMap, bool) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, false
	}
	if !hasJavaStructure(lines) {
		return digest.FileMap{}, false
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if javaGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	var blocks []*javaBlock
	var cur *javaBlock
	// pendingBlock holds a recognized type whose opening "{" has not yet
	// appeared (multi-line class/interface headers like
	//   public class Foo
	//       extends Bar
	//       implements Baz {
	// are uncommon but valid Java).
	var pendingBlock *javaBlock
	depth := 0
	inBlockComment := false
	inTextBlock := false // Java 15+ text blocks (""" ... """)

	closeBlock := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			blocks = append(blocks, cur)
			cur = nil
		}
	}

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" {
			continue
		}

		// Java 15+ text blocks.
		tripleCount := strings.Count(trimmed, `"""`)
		if inTextBlock {
			if tripleCount%2 == 1 {
				inTextBlock = false
			}
			continue
		}
		if tripleCount%2 == 1 {
			inTextBlock = true
			continue
		}

		// Block comment tracking.
		if inBlockComment {
			if strings.Contains(raw, "*/") {
				inBlockComment = false
			}
			continue
		}
		if javaBlockComment.MatchString(raw) {
			if !strings.Contains(raw, "*/") {
				inBlockComment = true
			}
			continue
		}
		if javaComment.MatchString(raw) {
			continue
		}

		// Waiting for the opening "{" of a multi-line class header.
		if pendingBlock != nil {
			d := javaNetBraces(raw)
			if d > 0 {
				cur = pendingBlock
				depth = d
				pendingBlock = nil
			} else if d < 0 {
				// Unexpected — discard rather than corrupt state.
				pendingBlock = nil
			}
			continue
		}

		if cur != nil {
			// Collect methods at depth 1 BEFORE updating depth so a
			// "void foo() {" line (depth 1→2) is correctly identified.
			if depth == 1 && !javaStaticInit.MatchString(raw) && !javaAnnotation.MatchString(raw) {
				if m := javaMethod.FindStringSubmatch(trimmed); m != nil {
					name := m[1]
					if !isJavaKeyword(name) {
						cur.methods = append(cur.methods, name)
					}
				}
			}
			depth += javaNetBraces(raw)
			if depth <= 0 {
				closeBlock(lineNo)
				depth = 0
			}
			continue
		}

		// Top-level type declaration. Check BEFORE the annotation guard so that
		// "@interface MyAnnotation {" (Java annotation type) is recognized as a
		// type declaration and not skipped as a standalone annotation line.
		if m := javaTopBlock.FindStringSubmatch(trimmed); m != nil {
			kind := strings.TrimSpace(m[1])
			b := &javaBlock{kind: kind, name: m[2], startLine: lineNo}
			d := javaNetBraces(raw)
			if d > 0 {
				cur = b
				depth = d
			} else {
				pendingBlock = b
			}
			continue
		}

		// Skip standalone annotation lines (e.g. @Component, @Override).
		if javaAnnotation.MatchString(raw) {
			continue
		}
	}
	closeBlock(len(lines))

	if len(blocks) == 0 {
		return digest.FileMap{}, false
	}

	var entries []digest.MapEntry
	var symbols []string
	for _, b := range blocks {
		label := javaBlockLabel(b)
		if len(symbols) < 40 {
			symbols = append(symbols, b.kind+" "+b.name)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(b.startLine, b.endLine),
			Kind:  label,
		})
	}

	return digest.FileMap{
		Summary: javaSummary(blocks, generated),
		Map:     entries,
		Symbols: symbols,
	}, true
}

// javaNetBraces counts net brace depth for a Java line, ignoring braces inside
// double-quoted strings, character literals, and after // comments.
func javaNetBraces(line string) int {
	depth := 0
	inStr := false
	for i := 0; i < len(line); i++ {
		ch := line[i]
		if inStr {
			if ch == '\\' {
				i++
				continue
			}
			if ch == '"' {
				inStr = false
			}
			continue
		}
		switch ch {
		case '"':
			inStr = true
		case '\'':
			i++
			for i < len(line) {
				if line[i] == '\\' {
					i++
				} else if line[i] == '\'' {
					break
				}
				i++
			}
		case '/':
			if i+1 < len(line) && line[i+1] == '/' {
				return depth
			}
		case '{':
			depth++
		case '}':
			depth--
		}
	}
	return depth
}

// isJavaKeyword reports whether s is a Java keyword that can appear as a
// false-positive match against the method-name capture group.
func isJavaKeyword(s string) bool {
	switch s {
	case "if", "for", "while", "switch", "return", "new", "throw", "catch",
		"try", "else", "do", "case", "break", "continue", "assert",
		"class", "interface", "enum", "record", "import", "package",
		"extends", "implements", "instanceof", "super", "this", "void", "var":
		return true
	}
	return false
}

// javaBlockLabel builds the Kind label for a Java block entry.
func javaBlockLabel(b *javaBlock) string {
	label := b.kind + " " + b.name
	if len(b.methods) == 0 {
		return label
	}
	displayed := b.methods
	suffix := ""
	if len(displayed) > 4 {
		displayed = displayed[:4]
		suffix = fmt.Sprintf(" (+%d)", len(b.methods)-4)
	}
	return label + " — " + strings.Join(displayed, ", ") + suffix
}

// javaSummary builds the top-level summary line.
func javaSummary(blocks []*javaBlock, generated bool) string {
	counts := map[string]int{}
	methodCount := 0
	for _, b := range blocks {
		counts[b.kind]++
		methodCount += len(b.methods)
	}

	ordered := []string{"class", "abstract class", "final class", "sealed class",
		"interface", "enum", "record", "@interface"}
	var parts []string
	for _, k := range ordered {
		n := counts[k]
		if n == 0 {
			continue
		}
		if n == 1 {
			parts = append(parts, "1 "+k)
		} else {
			words := strings.Fields(k)
			words[len(words)-1] += "s"
			parts = append(parts, fmt.Sprintf("%d %s", n, strings.Join(words, " ")))
		}
	}
	if methodCount == 1 {
		parts = append(parts, "1 method")
	} else if methodCount > 1 {
		parts = append(parts, fmt.Sprintf("%d methods", methodCount))
	}

	summary := "Java — " + strings.Join(parts, ", ")
	if generated {
		summary += " — generated, do not edit directly"
	}
	return summary
}

// hasJavaStructure returns true when at least one class/interface/enum/record
// declaration is present.
func hasJavaStructure(lines []string) bool {
	for _, l := range lines {
		if javaTopBlock.MatchString(l) {
			return true
		}
	}
	return false
}
