package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// kotlinTopBlock matches the opening of a top-level class, interface,
	// object, or enum class (with optional modifier keywords before it).
	// Visibility/scope modifiers (public/private/etc.) are consumed but not
	// captured; type-shaping modifiers (data/sealed/abstract/open/enum) ARE
	// included in group (1) so the kind label reads "data class", "sealed class".
	// Groups: (1) full kind phrase, (2) name
	kotlinTopBlock = regexp.MustCompile(
		`^\s*(?:(?:public|private|protected|internal|actual|expect)\s+)*` +
			`((?:(?:abstract|open|sealed|data|inner|inline|value|annotation)\s+)*(?:enum\s+)?(?:class|interface|object))\s+([A-Za-z_][A-Za-z0-9_]*)`)
	// kotlinCompanion matches "companion object" (may have a name or none).
	kotlinCompanion = regexp.MustCompile(`^\s*companion\s+object`)
	// kotlinFun matches a function definition, capturing the name.
	// Handles optional modifiers, extension receiver (Type.name), and suspend/inline/etc.
	// Groups: (1) name (possibly "Type.name" for extension funs)
	kotlinFun = regexp.MustCompile(
		`^\s*(?:(?:public|private|protected|internal|abstract|open|override|suspend|inline|tailrec|external|operator|infix|actual|expect|noinline|crossinline)\s+)*` +
			`fun\s+(?:<[^>]*>\s*)?(?:([A-Za-z_][A-Za-z0-9_.]*)\s*\.\s*)?([A-Za-z_][A-Za-z0-9_]*)`)
	// kotlinLineComment matches Kotlin single-line comments.
	kotlinComment = regexp.MustCompile(`^\s*//`)
	// kotlinBlockCommentStart matches the start of a /* block comment.
	kotlinBlockComment = regexp.MustCompile(`^\s*/\*`)
	// kotlinGenerated detects generated Kotlin files.
	kotlinGenerated = regexp.MustCompile(`@Generated|@generated|DO NOT EDIT|auto.?generated|This file was automatically generated|Generated by`)
	// kotlinTripleQuote detects multi-line string literals.
	kotlinTripleQuote = `"""`
)

// kotlinBlock tracks one top-level Kotlin definition while parsing.
type kotlinBlock struct {
	kind      string // "class", "data class", "sealed class", "interface", "object", "enum class"
	name      string
	startLine int
	endLine   int
	funs      []string // function names at depth 1
}

// parseKotlinFile builds a FileMap from a Kotlin source file. Each top-level
// class, interface, object, and companion object becomes one map entry. The
// Kind label lists function names (up to 4, with +N overflow).
func parseKotlinFile(src, _ string) (digest.FileMap, bool) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, false
	}

	if !hasKotlinStructure(lines) {
		return digest.FileMap{}, false
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if kotlinGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	var blocks []*kotlinBlock
	var cur *kotlinBlock
	// pendingBlock holds a recognized class/object/interface whose opening {
	// has not yet been seen (common with multi-line primary constructors:
	//   class Foo(
	//       val x: Int,
	//   ) {  ← brace is here, not on the class line
	// We keep scanning until we find the { or another top-level definition.
	var pendingBlock *kotlinBlock
	depth := 0
	inBlockComment := false
	inTripleQuote := false
	anonObjCount := 0

	closeBlock := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			blocks = append(blocks, cur)
			cur = nil
		}
	}

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" {
			continue
		}

		// Triple-quoted string literals can span lines and contain braces.
		// Toggle state on odd number of """ occurrences per line.
		tripleCount := strings.Count(trimmed, kotlinTripleQuote)
		if inTripleQuote {
			if tripleCount%2 == 1 {
				inTripleQuote = false
			}
			continue
		}
		if tripleCount%2 == 1 {
			inTripleQuote = true
			continue
		}

		// Block comment tracking.
		if inBlockComment {
			if strings.Contains(raw, "*/") {
				inBlockComment = false
			}
			continue
		}
		if kotlinBlockComment.MatchString(raw) {
			if !strings.Contains(raw, "*/") {
				inBlockComment = true
			}
			continue
		}
		if kotlinComment.MatchString(raw) {
			continue
		}

		// Waiting for the opening { of a multi-line class/object header.
		if pendingBlock != nil {
			// Check for a new top-level definition BEFORE testing for {.
			// A line like "sealed class Foo {" starts a new definition — it is
			// NOT the body opener for the pending class (which has no body).
			isNewDef := kotlinTopBlock.MatchString(trimmed) ||
				kotlinFun.MatchString(trimmed) ||
				kotlinCompanion.MatchString(trimmed)
			if isNewDef {
				// The pending class has no body (e.g. data class with only
				// primary constructor params).
				pendingBlock.endLine = lineNo - 1
				blocks = append(blocks, pendingBlock)
				pendingBlock = nil
				// fall through to process this line as the new definition
			} else {
				d := kotlinNetBraces(raw)
				if d > 0 {
					cur = pendingBlock
					depth = d
					pendingBlock = nil
				}
				continue
			}
		}

		if cur != nil {
			// Record functions at depth 1 BEFORE updating depth, so a "fun foo() {"
			// line (which takes depth from 1 → 2) is correctly identified as a
			// member of the current block.
			if depth == 1 {
				if m := kotlinFun.FindStringSubmatch(trimmed); m != nil {
					name := kotlinFunName(m[1], m[2])
					cur.funs = append(cur.funs, name)
				}
			}
			depth += kotlinNetBraces(raw)
			if depth <= 0 {
				closeBlock(lineNo)
				depth = 0
			}
			continue
		}

		// companion object (may be unnamed)
		if kotlinCompanion.MatchString(trimmed) {
			anonObjCount++
			name := fmt.Sprintf("companion object #%d", anonObjCount)
			b := &kotlinBlock{kind: "companion object", name: name, startLine: lineNo}
			d := kotlinNetBraces(raw)
			if d > 0 {
				cur = b
				depth = d
			} else {
				pendingBlock = b
			}
			continue
		}

		// class / interface / object / enum class
		if m := kotlinTopBlock.FindStringSubmatch(trimmed); m != nil {
			// Trim trailing whitespace from the kind (e.g. "data class " → "data class").
			kind := strings.TrimSpace(m[1])
			b := &kotlinBlock{kind: kind, name: m[2], startLine: lineNo}
			d := kotlinNetBraces(raw)
			if d > 0 {
				cur = b
				depth = d
			} else {
				pendingBlock = b
			}
			continue
		}

		// Top-level function (not inside a class).
		if m := kotlinFun.FindStringSubmatch(trimmed); m != nil {
			name := kotlinFunName(m[1], m[2])
			b := &kotlinBlock{kind: "fun", name: name, startLine: lineNo}
			d := kotlinNetBraces(raw)
			if d > 0 {
				cur = b
				depth = d
			} else {
				// Single-expression top-level function (fun foo() = expr).
				b.endLine = lineNo
				blocks = append(blocks, b)
			}
			continue
		}
	}

	// Close any class still open (pendingBlock with no body found → single-line header).
	if pendingBlock != nil {
		pendingBlock.endLine = len(lines)
		blocks = append(blocks, pendingBlock)
	}
	closeBlock(len(lines))

	if len(blocks) == 0 {
		return digest.FileMap{}, false
	}

	var entries []digest.MapEntry
	var symbols []string

	for _, b := range blocks {
		label := kotlinBlockLabel(b)
		sym := b.kind + " " + b.name
		if len(symbols) < 40 {
			symbols = append(symbols, sym)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(b.startLine, b.endLine),
			Kind:  label,
		})
	}

	summary := kotlinSummary(blocks, generated)

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
	}, true
}

// kotlinNetBraces counts net brace depth for a Kotlin line, ignoring braces
// inside double-quoted strings and after // comments. Triple-quoted strings
// are handled at the line level before this function is called.
func kotlinNetBraces(line string) int {
	depth := 0
	inStr := false
	for i := 0; i < len(line); i++ {
		ch := line[i]
		if inStr {
			if ch == '\\' {
				i++
				continue
			}
			if ch == '"' {
				inStr = false
			}
			continue
		}
		switch ch {
		case '"':
			inStr = true
		case '/':
			if i+1 < len(line) && line[i+1] == '/' {
				return depth
			}
		case '{':
			depth++
		case '}':
			depth--
		}
	}
	return depth
}

// kotlinFunName builds a display name for a function.
// receiver is the extension receiver type (e.g. "String" in "fun String.foo()"),
// name is the function name itself.
func kotlinFunName(receiver, name string) string {
	if receiver != "" {
		return receiver + "." + name
	}
	return name
}

// kotlinBlockLabel builds the Kind label for a Kotlin block entry.
func kotlinBlockLabel(b *kotlinBlock) string {
	label := b.kind + " " + b.name
	if len(b.funs) == 0 {
		return label
	}
	displayed := b.funs
	suffix := ""
	if len(displayed) > 4 {
		displayed = displayed[:4]
		suffix = fmt.Sprintf(" (+%d)", len(b.funs)-4)
	}
	return label + " — " + strings.Join(displayed, ", ") + suffix
}

// kotlinSummary builds the top-level summary line.
func kotlinSummary(blocks []*kotlinBlock, generated bool) string {
	counts := map[string]int{}
	funCount := 0
	for _, b := range blocks {
		counts[b.kind]++
		funCount += len(b.funs)
	}

	// Normalize for display.
	ordered := []string{"class", "data class", "sealed class", "enum class", "interface", "object", "companion object", "fun"}
	var parts []string
	for _, k := range ordered {
		n := counts[k]
		if n == 0 {
			continue
		}
		if n == 1 {
			parts = append(parts, "1 "+k)
		} else {
			// pluralize the last word
			words := strings.Fields(k)
			words[len(words)-1] += "s"
			parts = append(parts, fmt.Sprintf("%d %s", n, strings.Join(words, " ")))
		}
	}
	if funCount > 0 {
		if funCount == 1 {
			parts = append(parts, "1 method")
		} else {
			parts = append(parts, fmt.Sprintf("%d methods", funCount))
		}
	}

	summary := "Kotlin — " + strings.Join(parts, ", ")
	if generated {
		summary += " — generated, do not edit directly"
	}
	return summary
}

// hasKotlinStructure returns true when at least one top-level class, interface,
// object, or function definition is found.
func hasKotlinStructure(lines []string) bool {
	for _, l := range lines {
		t := strings.TrimSpace(l)
		if kotlinTopBlock.MatchString(t) || kotlinFun.MatchString(t) || kotlinCompanion.MatchString(t) {
			return true
		}
	}
	return false
}
