package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// makeTarget matches an explicit target: a non-empty name at the start of
	// a line followed by a colon, optionally with prerequisites. Pattern rules
	// (containing % or $) are excluded.
	makeTarget = regexp.MustCompile(`^([A-Za-z0-9._/\-]+)\s*:(?:[^=]|$)`)
	// makePhony matches a .PHONY declaration line.
	makePhony = regexp.MustCompile(`^\.PHONY\s*:(.*)`)
	// makeVarDef matches a variable assignment (excluded from targets).
	makeVarDef = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*\s*[:?+!]?=`)
	// makeComment is a Makefile comment.
	makeComment = regexp.MustCompile(`^\s*#`)
	// makeRecipe is an indented recipe line (tab-prefixed).
	makeRecipe = regexp.MustCompile(`^\t`)
	// makeGenerated marks generated Makefiles.
	makeGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|autogenerated`)
)

// makefileTarget tracks one Makefile target block while parsing.
type makefileTarget struct {
	name      string
	startLine int
	endLine   int
	recipe    string // first non-comment recipe line
	isPhony   bool
}

// parseMakefile builds a FileMap from a Makefile. Targets are the primary
// structural unit; the map has one entry per target with the first non-comment
// recipe line as a hint. PHONY targets are flagged. Pattern rules and variable
// assignments are skipped.
const maxMakefileTargets = 40

func parseMakefile(src, _ string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasMakefileStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no targets found")
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if makeGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	// Collect PHONY targets from all .PHONY lines.
	phony := map[string]bool{}
	for _, l := range lines {
		if m := makePhony.FindStringSubmatch(l); m != nil {
			for _, t := range strings.Fields(m[1]) {
				phony[t] = true
			}
		}
	}

	var targets []*makefileTarget
	var cur *makefileTarget

	closeTarget := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			targets = append(targets, cur)
		}
	}

	for i, raw := range lines {
		lineNo := i + 1

		// Recipe line: belongs to the current target.
		if makeRecipe.MatchString(raw) {
			if cur != nil && cur.recipe == "" {
				trimmed := strings.TrimSpace(raw)
				if trimmed != "" && !makeComment.MatchString(trimmed) {
					cur.recipe = trimmed
				}
			}
			continue
		}

		// Blank line or comment at column 0: keep current target open (targets
		// can have blank lines between recipe lines).
		trimmed := strings.TrimSpace(raw)
		if trimmed == "" || makeComment.MatchString(raw) {
			continue
		}

		// Skip .PHONY lines and variable assignments.
		if makePhony.MatchString(raw) || makeVarDef.MatchString(raw) {
			continue
		}

		if m := makeTarget.FindStringSubmatch(raw); m != nil {
			name := m[1]
			// Skip built-in and meta targets.
			if strings.HasPrefix(name, ".") {
				continue
			}
			closeTarget(lineNo - 1)
			cur = &makefileTarget{
				name:      name,
				startLine: lineNo,
				isPhony:   phony[name],
			}
			continue
		}

		// Any other non-recipe, non-blank line closes the current target
		// (e.g. a multi-line variable definition body).
		if cur != nil {
			closeTarget(lineNo - 1)
			cur = nil
		}
	}
	closeTarget(len(lines))

	if len(targets) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: no targets found")
	}

	var entries []digest.MapEntry
	var symbols []string

	for _, t := range targets {
		if len(symbols) < 40 {
			symbols = append(symbols, t.name)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(t.startLine, t.endLine),
			Kind:  makeTargetKindLabel(t),
		})
	}

	summary := fmt.Sprintf("Makefile — %d target(s)", len(targets))
	if generated {
		summary += " — generated, do not edit directly"
	}

	var notes string
	if len(targets) > maxMakefileTargets {
		notes = fmt.Sprintf("showing first %d of %d targets", maxMakefileTargets, len(targets))
	}

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
		Notes:   notes,
	}, nil
}

// makeTargetKindLabel builds the Kind label for one Makefile target.
func makeTargetKindLabel(t *makefileTarget) string {
	label := t.name
	if t.isPhony {
		label += " (phony)"
	}
	if t.recipe != "" {
		// Truncate long recipe hints.
		r := t.recipe
		if len(r) > 60 {
			r = r[:57] + "..."
		}
		label += ": " + r
	}
	return label
}

// hasMakefileStructure returns true when at least one explicit target is present.
func hasMakefileStructure(lines []string) bool {
	for _, l := range lines {
		if makeTarget.MatchString(l) && !makeVarDef.MatchString(l) {
			name := makeTarget.FindStringSubmatch(l)[1]
			if !strings.HasPrefix(name, ".") {
				return true
			}
		}
	}
	return false
}
