package filemap_test

import (
	"strings"
	"testing"

	"github.com/kaushal/skim/internal/filemap"
)

// TestGenerate_CargoLock_FallsThrough verifies that Cargo.lock is excluded
// from TOML parsing. Its content is version-pinned dependency data that the
// model must read verbatim; a structural digest would be wrong.
func TestGenerate_CargoLock_FallsThrough(t *testing.T) {
	src := `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.210"
source = "registry+https://github.com/rust-lang/crates.io-index"
`
	_, ok := filemap.Generate(src, "Cargo.lock")
	if ok {
		t.Error("Cargo.lock must fall through — its content must reach the model verbatim")
	}
}

// TestGenerate_DefaultPassthroughGlobs verifies the set of filenames that must
// always be treated as passthrough by the detect layer. These are tested via
// the filemap.Generate exclusion (lock files, credential files) rather than
// the config layer, but the names are the same.
func TestGenerate_PassthroughLockFiles(t *testing.T) {
	// These lock file formats don't have their own parsers; the passthrough
	// protection comes from the default PassthroughGlobs in config.Default().
	// Here we verify that the ones that DO have parsers also fall through.
	cases := []struct {
		name    string
		src     string
	}{
		// JSON lock files (handled in json.go lockFileNames)
		{"package-lock.json", `{"lockfileVersion": 3, "packages": {}}`},
		{"npm-shrinkwrap.json", `{"lockfileVersion": 2, "packages": {}}`},
		{"composer.lock", `{"_readme": [], "packages": []}`},
		// TOML lock files (handled in toml.go tomlLockFileNames)
		{"Cargo.lock", "version = 3\n[[package]]\nname = \"serde\"\n"},
	}
	for _, tc := range cases {
		_, ok := filemap.Generate(tc.src, tc.name)
		if ok {
			t.Errorf("%s must fall through to the worker — got a map", tc.name)
		}
	}
}

// TestGenerate_RegularTOMLNotLockFile ensures that a valid, non-lock TOML file
// still gets a deterministic map (regression guard: the Cargo.lock exclusion
// must not accidentally catch real Cargo.toml files).
func TestGenerate_RegularTOMLNotLockFile(t *testing.T) {
	src := "[package]\nname = \"my-crate\"\nversion = \"0.1.0\"\n"
	fm, ok := filemap.Generate(src, "Cargo.toml")
	if !ok {
		t.Error("Cargo.toml should still produce a deterministic map")
	}
	if !strings.Contains(fm.Summary, "Cargo") {
		t.Errorf("expected Cargo summary, got: %s", fm.Summary)
	}
}
