package filemap_test

import (
	"strings"
	"testing"

	"github.com/kaushal/skim/internal/filemap"
)

func TestGenerate_Proto_MessagesAndServices(t *testing.T) {
	src := `syntax = "proto3";

package search.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/example/search/v1";

message SearchRequest {
  string query = 1;
  int32  page_number = 2;
  int32  result_per_page = 3;
}

message SearchResponse {
  repeated Result results = 1;
  int32 total = 2;
}

message Result {
  string url   = 1;
  string title = 2;
}

service SearchService {
  rpc Search(SearchRequest) returns (SearchResponse);
  rpc StreamSearch(SearchRequest) returns (stream SearchResponse);
}
`
	fm, ok := filemap.Generate(src, "search.proto")
	if !ok {
		t.Fatal("expected deterministic map for proto file")
	}

	if !strings.Contains(fm.Summary, "package search.v1") {
		t.Errorf("expected package in summary, got: %s", fm.Summary)
	}
	if !strings.Contains(fm.Summary, "message") {
		t.Errorf("expected message count in summary, got: %s", fm.Summary)
	}
	if !strings.Contains(fm.Summary, "service") {
		t.Errorf("expected service in summary, got: %s", fm.Summary)
	}

	symbolSet := map[string]bool{}
	for _, s := range fm.Symbols {
		symbolSet[s] = true
	}
	for _, want := range []string{"message SearchRequest", "message SearchResponse", "message Result", "service SearchService"} {
		if !symbolSet[want] {
			t.Errorf("expected symbol %q in %v", want, fm.Symbols)
		}
	}

	// Service Kind label should list RPCs.
	var serviceEntry string
	for _, e := range fm.Map {
		if strings.Contains(e.Kind, "service SearchService") {
			serviceEntry = e.Kind
		}
	}
	if !strings.Contains(serviceEntry, "Search") || !strings.Contains(serviceEntry, "StreamSearch") {
		t.Errorf("service entry should list RPCs, got: %s", serviceEntry)
	}
}

func TestGenerate_Proto_EnumBlocks(t *testing.T) {
	src := `syntax = "proto3";
package status.v1;

enum Status {
  STATUS_UNKNOWN  = 0;
  STATUS_ACTIVE   = 1;
  STATUS_INACTIVE = 2;
  STATUS_DELETED  = 3;
}

message Item {
  string name   = 1;
  Status status = 2;
}
`
	fm, ok := filemap.Generate(src, "status.proto")
	if !ok {
		t.Fatal("expected deterministic map")
	}

	symbolSet := map[string]bool{}
	for _, s := range fm.Symbols {
		symbolSet[s] = true
	}
	if !symbolSet["enum Status"] {
		t.Errorf("expected 'enum Status' in %v", fm.Symbols)
	}
	if !symbolSet["message Item"] {
		t.Errorf("expected 'message Item' in %v", fm.Symbols)
	}
}

func TestGenerate_Proto_LineRangesNoOverlap(t *testing.T) {
	src := `syntax = "proto3";
package test.v1;

message Alpha {
  string name = 1;
}

message Beta {
  int32 value = 2;
}

message Gamma {
  bool flag = 3;
}
`
	fm, ok := filemap.Generate(src, "test.proto")
	if !ok {
		t.Fatal("expected deterministic map")
	}
	if len(fm.Map) != 3 {
		t.Fatalf("expected 3 entries, got %d", len(fm.Map))
	}
	for _, e := range fm.Map {
		if e.Lines == "" {
			t.Errorf("entry has empty Lines: %+v", e)
		}
	}
	// Alpha starts at line 4.
	if !strings.HasPrefix(fm.Map[0].Lines, "4") {
		t.Errorf("Alpha should start on line 4, got: %s", fm.Map[0].Lines)
	}
}

func TestGenerate_Proto_BraceInString(t *testing.T) {
	// A closing brace inside a string option must not close the block early.
	src := `syntax = "proto3";

message Config {
  option (validate.required) = true;
  string pattern = 1 [(validate.rules).string = {min_len: 1}];
  string desc = 2;
}

message Other {
  string value = 1;
}
`
	fm, ok := filemap.Generate(src, "config.proto")
	if !ok {
		t.Fatal("expected deterministic map")
	}
	if len(fm.Map) != 2 {
		t.Fatalf("expected 2 entries (brace in string closed first block early), got %d: %v", len(fm.Map), fm.Map)
	}
}

func TestGenerate_Proto_GeneratedFile(t *testing.T) {
	src := `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

syntax = "proto3";

message Generated {
  string field = 1;
}
`
	fm, ok := filemap.Generate(src, "search.pb.go")
	// .pb.go files are Go, not proto — pass as .proto to test the proto parser
	_ = fm
	_ = ok
	// Test via a .proto file path
	fm, ok = filemap.Generate(src, "gen.proto")
	if !ok {
		t.Fatal("expected deterministic map for generated proto")
	}
	if !strings.Contains(fm.Summary, "generated") {
		t.Errorf("expected 'generated' in summary, got: %s", fm.Summary)
	}
}

func TestGenerate_Proto_FallsThrough_Empty(t *testing.T) {
	_, ok := filemap.Generate("", "service.proto")
	if ok {
		t.Error("expected fallthrough for empty proto file")
	}
}

func TestGenerate_Proto_FallsThrough_NoBlocks(t *testing.T) {
	// A file with only syntax/package/import lines has no blocks.
	src := `syntax = "proto3";
package test.v1;
import "google/protobuf/empty.proto";
`
	_, ok := filemap.Generate(src, "empty.proto")
	if ok {
		t.Error("expected fallthrough for proto file with no message/service/enum blocks")
	}
}

func TestGenerate_Proto_ServiceRPCsInKind(t *testing.T) {
	// RPCs should appear in the service's Kind label (up to 4).
	src := `syntax = "proto3";
package gateway.v1;

message Req {}
message Res {}

service GatewayService {
  rpc Create(Req) returns (Res);
  rpc Read(Req) returns (Res);
  rpc Update(Req) returns (Res);
  rpc Delete(Req) returns (Res);
  rpc List(Req) returns (Res);
}
`
	fm, ok := filemap.Generate(src, "gateway.proto")
	if !ok {
		t.Fatal("expected deterministic map")
	}
	var svcEntry string
	for _, e := range fm.Map {
		if strings.Contains(e.Kind, "service GatewayService") {
			svcEntry = e.Kind
		}
	}
	if svcEntry == "" {
		t.Fatal("expected service entry in map")
	}
	// 5 RPCs — should show first 4 and (+1) suffix.
	if !strings.Contains(svcEntry, "(+1)") {
		t.Errorf("expected (+1) for 5th RPC, got: %s", svcEntry)
	}
	if !strings.Contains(svcEntry, "Create") {
		t.Errorf("expected Create in RPC list, got: %s", svcEntry)
	}
}
