package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// protoTopBlock matches a top-level proto block opener.
	// Groups: (1) block type, (2) name
	protoTopBlock = regexp.MustCompile(`^(message|service|enum|extend)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{`)
	// protoRPC matches an rpc definition inside a service block.
	// Groups: (1) rpc name, (2) request type, (3) response type
	protoRPC = regexp.MustCompile(`^\s*rpc\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s+returns\s+\(([^)]*)\)`)
	// protoPackage extracts the package name.
	protoPackage = regexp.MustCompile(`^package\s+([A-Za-z_][A-Za-z0-9_.]*)\s*;`)
	// protoComment matches proto line comments.
	protoComment = regexp.MustCompile(`^\s*//`)
	// protoBlockComment matches the start of a /* block comment.
	protoBlockComment = regexp.MustCompile(`^\s*/\*`)
	// protoGenerated marks generated proto files.
	protoGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|Code generated by`)
)

// protoBlock tracks one top-level proto block while parsing.
type protoBlock struct {
	kind      string // message, service, enum, extend
	name      string
	startLine int
	endLine   int
	rpcs      []string // service blocks: rpc names in order
}

// parseProtoFile builds a FileMap from a .proto file. Each top-level message,
// service, enum, and extend block becomes one map entry. Service blocks list
// their RPCs in the Kind label.
func parseProtoFile(src, filePath string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasProtoStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no proto block structure found")
	}

	generated := false
	pkg := ""
	for _, l := range lines[:min(len(lines), 10)] {
		if protoGenerated.MatchString(l) {
			generated = true
		}
		if m := protoPackage.FindStringSubmatch(strings.TrimSpace(l)); m != nil {
			pkg = m[1]
		}
	}

	var blocks []*protoBlock
	var cur *protoBlock
	depth := 0

	closeBlock := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			blocks = append(blocks, cur)
			cur = nil
		}
	}

	inBlockComment := false

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" {
			continue
		}

		// Block comment tracking.
		if inBlockComment {
			if strings.Contains(raw, "*/") {
				inBlockComment = false
			}
			continue
		}
		if protoBlockComment.MatchString(raw) {
			if !strings.Contains(raw, "*/") {
				inBlockComment = true
			}
			continue
		}
		if protoComment.MatchString(raw) {
			continue
		}

		// Inside a block: track depth and collect RPCs.
		if cur != nil {
			depth += protoNetBraces(raw)
			if depth <= 0 {
				closeBlock(lineNo)
				depth = 0
				continue
			}
			// Collect rpc definitions inside service blocks (depth == 1 means
			// we are at the direct child level of the service body).
			if cur.kind == "service" && depth == 1 {
				if m := protoRPC.FindStringSubmatch(raw); m != nil {
					cur.rpcs = append(cur.rpcs, m[1])
				}
			}
			continue
		}

		// Looking for a new top-level block.
		if m := protoTopBlock.FindStringSubmatch(trimmed); m != nil {
			cur = &protoBlock{
				kind:      m[1],
				name:      m[2],
				startLine: lineNo,
			}
			depth = protoNetBraces(raw)
		}
	}
	closeBlock(len(lines))

	if len(blocks) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: no proto blocks found")
	}

	var entries []digest.MapEntry
	var symbols []string

	for _, b := range blocks {
		label := protoBlockLabel(b)
		if len(symbols) < 40 {
			symbols = append(symbols, b.kind+" "+b.name)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(b.startLine, b.endLine),
			Kind:  label,
		})
	}

	summary := protoSummary(pkg, blocks, generated)

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
	}, nil
}

// protoNetBraces counts net brace depth change for a proto line, ignoring
// braces inside double-quoted strings and after // comments.
func protoNetBraces(line string) int {
	depth := 0
	inStr := false
	for i := 0; i < len(line); i++ {
		ch := line[i]
		if inStr {
			if ch == '\\' {
				i++
				continue
			}
			if ch == '"' {
				inStr = false
			}
			continue
		}
		switch ch {
		case '"':
			inStr = true
		case '/':
			if i+1 < len(line) && line[i+1] == '/' {
				return depth
			}
		case '{':
			depth++
		case '}':
			depth--
		}
	}
	return depth
}

// protoBlockLabel builds the display label for one proto block.
func protoBlockLabel(b *protoBlock) string {
	label := b.kind + " " + b.name
	if b.kind == "service" && len(b.rpcs) > 0 {
		displayed := b.rpcs
		suffix := ""
		if len(displayed) > 4 {
			displayed = displayed[:4]
			suffix = fmt.Sprintf(" (+%d)", len(b.rpcs)-4)
		}
		label += " — " + strings.Join(displayed, ", ") + suffix
	}
	return label
}

// protoSummary builds the top-level summary line.
func protoSummary(pkg string, blocks []*protoBlock, generated bool) string {
	counts := map[string]int{}
	for _, b := range blocks {
		counts[b.kind]++
	}

	ordered := []string{"message", "service", "enum", "extend"}
	var parts []string
	for _, t := range ordered {
		if n := counts[t]; n > 0 {
			if n == 1 {
				parts = append(parts, fmt.Sprintf("1 %s", t))
			} else {
				parts = append(parts, fmt.Sprintf("%d %ss", n, t))
			}
		}
	}

	var prefix string
	if pkg != "" {
		prefix = "package " + pkg
	} else {
		prefix = "Proto file"
	}

	summary := prefix + " — " + strings.Join(parts, ", ")
	if generated {
		summary += " — generated, do not edit directly"
	}
	return summary
}

// hasProtoStructure returns true when at least one recognized proto block
// is present.
func hasProtoStructure(lines []string) bool {
	for _, l := range lines {
		if protoTopBlock.MatchString(strings.TrimSpace(l)) {
			return true
		}
	}
	return false
}
