package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	pyImportLine  = regexp.MustCompile(`^(?:import|from)\s+`)
	pyClassDecl   = regexp.MustCompile(`^class\s+(\w+)`)
	pyFuncDecl    = regexp.MustCompile(`^(?:async\s+)?def\s+(\w+)`)
	pyMethodDecl  = regexp.MustCompile(`^\s{4}(?:async\s+)?def\s+(\w+)`) // one indent level
	pyDecorator   = regexp.MustCompile(`^@\w+`)
	pyDocstring   = regexp.MustCompile(`^"""(.*)`)
	pyAllDecl     = regexp.MustCompile(`^__all__\s*=`)
	pyGenerated   = regexp.MustCompile(`@generated|DO NOT EDIT|Code generated|autogenerated`)
)

// parsePyFile builds a FileMap from a Python source file. It uses line
// scanning with Python's indentation-based block structure: module-level
// declarations are at column 0, method definitions are at one indent level
// (4 spaces). This is intentionally permissive — tabs and non-standard
// indentation fall through to the worker.
func parsePyFile(src, filePath string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasPyStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no recognizable Python structure")
	}

	// Check for generated file markers in the first few lines.
	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if pyGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	// Extract module docstring (first triple-quoted string at the top of the
	// file, before any imports or declarations).
	moduleSummary := extractPyDocstring(lines)

	var (
		entries     []digest.MapEntry
		symbols     []string
		seenSymbols = map[string]bool{}
	)

	addSymbol := func(name string) {
		if name != "" && !seenSymbols[name] && len(symbols) < 40 {
			symbols = append(symbols, name)
			seenSymbols[name] = true
		}
	}

	// Section scanner state.
	importStart, importEnd := 0, 0
	inClass := false
	classStart := 0
	className := ""
	var classMethods []string

	closeClass := func(endLine int) {
		if !inClass {
			return
		}
		kind := fmt.Sprintf("class %s", className)
		if len(classMethods) > 0 {
			shown := classMethods
			if len(shown) > 5 {
				shown = shown[:5]
			}
			kind = fmt.Sprintf("class %s — methods: %s", className, strings.Join(shown, ", "))
			if len(classMethods) > 5 {
				kind += fmt.Sprintf(" (+%d more)", len(classMethods)-5)
			}
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(classStart, endLine),
			Kind:  kind,
		})
		inClass = false
		className = ""
		classMethods = nil
		classStart = 0
	}

	pendingDecorator := 0 // line number of the most recent @decorator

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		// Decorator: note the line for the next function/class.
		if pyDecorator.MatchString(raw) {
			if pendingDecorator == 0 {
				pendingDecorator = lineNo
			}
			continue
		}

		// Module-level import
		if pyImportLine.MatchString(raw) {
			if importStart == 0 {
				importStart = lineNo
			}
			importEnd = lineNo
			pendingDecorator = 0
			continue
		}

		// __all__: a structural landmark even if not a function/class.
		if pyAllDecl.MatchString(raw) {
			addSymbol("__all__")
			entries = append(entries, digest.MapEntry{
				Lines: lineRange(lineNo, lineNo),
				Kind:  "__all__ — public API declaration",
			})
			pendingDecorator = 0
			continue
		}

		// Module-level class declaration (starts at column 0).
		if pyClassDecl.MatchString(raw) {
			m := pyClassDecl.FindStringSubmatch(raw)
			name := m[1]
			addSymbol(name)

			// Close any previous class.
			closeClass(lineNo - 1)

			declLine := lineNo
			if pendingDecorator > 0 {
				declLine = pendingDecorator
				pendingDecorator = 0
			}

			inClass = true
			className = name
			classStart = declLine
			continue
		}

		// Method inside a class (indented def).
		if inClass && pyMethodDecl.MatchString(raw) {
			m := pyMethodDecl.FindStringSubmatch(raw)
			if len(m) > 1 {
				classMethods = append(classMethods, m[1])
			}
			pendingDecorator = 0
			continue
		}

		// Module-level function declaration (starts at column 0).
		if pyFuncDecl.MatchString(raw) {
			m := pyFuncDecl.FindStringSubmatch(raw)
			name := m[1]
			addSymbol(name)

			// Close any previous class.
			closeClass(lineNo - 1)

			declLine := lineNo
			if pendingDecorator > 0 {
				declLine = pendingDecorator
				pendingDecorator = 0
			}

			entries = append(entries, digest.MapEntry{
				Lines: lineRange(declLine, declLine),
				Kind:  fmt.Sprintf("def %s", name),
			})
			continue
		}

		// If we hit something unindented that's not a class/func/import, close
		// any open class.
		if len(raw) > 0 && raw[0] != ' ' && raw[0] != '\t' {
			closeClass(lineNo - 1)
		}

		pendingDecorator = 0
	}

	closeClass(len(lines))

	// Build entries in order.
	var result []digest.MapEntry
	if importStart > 0 {
		result = append(result, digest.MapEntry{
			Lines: lineRange(importStart, importEnd),
			Kind:  "imports",
		})
	}
	result = append(result, entries...)

	if len(result) == 0 {
		result = []digest.MapEntry{{Lines: lineRange(1, len(lines)), Kind: "module body"}}
	}

	// Summary.
	summary := moduleSummary
	if summary == "" {
		summary = "Python module"
	}
	if generated {
		summary += " — generated file, do not edit directly"
	}

	var notes string
	if generated {
		notes = "generated file — edit the generator, not this file"
	}

	// Give the entry line ranges more precision: for function entries that are
	// single-line, try to find where the function body ends by looking for the
	// next module-level declaration.
	result = extendPyFuncRanges(result, lines)

	return digest.FileMap{
		Summary: summary,
		Map:     result,
		Symbols: symbols,
		Notes:   notes,
	}, nil
}

// hasPyStructure returns true when the source contains at least one Python-like
// construct. Rejects non-Python files that happen to have a .py extension.
func hasPyStructure(lines []string) bool {
	for _, l := range lines {
		if pyImportLine.MatchString(l) || pyClassDecl.MatchString(l) || pyFuncDecl.MatchString(l) {
			return true
		}
	}
	return false
}

// extractPyDocstring returns the first line of a module-level docstring, if
// the file begins with one (possibly after a shebang or encoding comment).
func extractPyDocstring(lines []string) string {
	for _, l := range lines {
		t := strings.TrimSpace(l)
		if t == "" || strings.HasPrefix(t, "#") {
			continue
		}
		if m := pyDocstring.FindStringSubmatch(t); m != nil {
			first := strings.TrimSpace(m[1])
			if first != "" && first != `"""` {
				// Inline docstring: "first line of triple-quoted string"
				first = strings.TrimSuffix(first, `"""`)
				first = strings.TrimSpace(first)
				if first != "" {
					return first
				}
			}
		}
		break
	}
	return ""
}

// extendPyFuncRanges replaces single-line function entries with a range ending
// just before the next module-level declaration. This makes `def foo` entries
// span the whole function body rather than just the signature line.
func extendPyFuncRanges(entries []digest.MapEntry, lines []string) []digest.MapEntry {
	// Build a list of "module-level declaration line numbers" from the entries.
	declLines := make(map[int]bool)
	for _, e := range entries {
		var start int
		fmt.Sscanf(e.Lines, "%d", &start)
		declLines[start] = true
	}

	result := make([]digest.MapEntry, len(entries))
	copy(result, entries)

	for i := range result {
		var start int
		fmt.Sscanf(result[i].Lines, "%d", &start)
		if !strings.Contains(result[i].Lines, "-") && strings.HasPrefix(result[i].Kind, "def ") {
			// Single-line def entry: extend to just before the next decl.
			end := len(lines)
			for _, e := range entries {
				var next int
				fmt.Sscanf(e.Lines, "%d", &next)
				if next > start && next < end {
					end = next - 1
				}
			}
			if end > start {
				result[i].Lines = lineRange(start, end)
			}
		}
	}
	return result
}
