package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// rubyClassMod matches class and module openers.
	// Group (1): keyword ("class" or "module"), (2): name (may include :: and <)
	rubyClassMod = regexp.MustCompile(`^\s*(class|module)\s+([A-Z][A-Za-z0-9_:]*)`)
	// rubyDef matches method definitions.
	// Group (1): optional "self.", (2): method name (may include ? or ! suffix)
	rubyDef = regexp.MustCompile(`^\s*def\s+((?:self\.)?)([A-Za-z_][A-Za-z0-9_?!]*)`)
	// rubyEnd matches a bare "end" line (closes any block).
	rubyEnd = regexp.MustCompile(`^\s*end\s*(?:#.*)?$`)
	// rubyOpener matches block-opening keywords other than class/module/def.
	// These must be counted to keep depth in sync with end keywords.
	rubyOpener = regexp.MustCompile(`^\s*(?:if|unless|while|until|for|begin|case|do)\b`)
	// rubyDoBlock matches " do" or " do |vars|" at the end of a line.
	// method calls with do..end blocks add one depth level.
	rubyDoBlock = regexp.MustCompile(`\bdo\s*(?:\|[^|]*\|)?\s*(?:#.*)?$`)
	// rubyOneliner matches a def that ends on the same line (one-liner method).
	rubyOneliner = regexp.MustCompile(`^\s*def\s+.*\bend\b`)
	// rubyComment matches Ruby line comments.
	rubyComment = regexp.MustCompile(`^\s*#`)
	// rubyHeredocOpen matches the start of a heredoc: <<~MARKER or <<-MARKER or <<MARKER
	rubyHeredoc = regexp.MustCompile(`<<[-~]?([A-Za-z_][A-Za-z0-9_]*)`)
	// rubyGenerated detects generated Ruby files.
	rubyGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|auto.?generated|This file was automatically generated|Generated by`)
)

// rubyBlock tracks one class or module while parsing.
type rubyBlock struct {
	kind      string // "class" or "module"
	name      string
	startLine int
	endLine   int
	methods   []string
}

// parseRubyFile builds a FileMap from a Ruby source file. Each top-level
// class and module definition becomes one map entry. The Kind label lists
// method names (up to 4, with a +N overflow suffix).
func parseRubyFile(src, _ string) (digest.FileMap, bool) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, false
	}

	if !hasRubyStructure(lines) {
		return digest.FileMap{}, false
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if rubyGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	var blocks []*rubyBlock
	var cur *rubyBlock
	depth := 0 // 0 = top level; 1 = inside a class/module body
	heredocMarker := ""

	closeBlock := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			blocks = append(blocks, cur)
			cur = nil
		}
	}

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" {
			continue
		}

		// Heredoc body: skip until the closing marker.
		if heredocMarker != "" {
			if strings.TrimSpace(raw) == heredocMarker {
				heredocMarker = ""
			}
			continue
		}

		// Detect heredoc opening on this line.
		if m := rubyHeredoc.FindStringSubmatch(raw); m != nil {
			heredocMarker = m[1]
			// Fall through: the opening line may still contain structural keywords.
		}

		if rubyComment.MatchString(raw) {
			continue
		}

		// One-liner methods (def foo; ...; end) do not change net depth.
		if rubyOneliner.MatchString(raw) {
			if cur != nil && depth == 1 {
				if m := rubyDef.FindStringSubmatch(raw); m != nil {
					name := rubyMethodName(m[1], m[2])
					cur.methods = append(cur.methods, name)
				}
			}
			continue
		}

		// class / module opener
		if m := rubyClassMod.FindStringSubmatch(raw); m != nil {
			if depth == 0 {
				// Nested class/module: close the previous block if any.
				closeBlock(lineNo - 1)
				cur = &rubyBlock{kind: m[1], name: m[2], startLine: lineNo}
			}
			depth++
			continue
		}

		// Method definition
		if m := rubyDef.FindStringSubmatch(raw); m != nil {
			if cur != nil && depth == 1 {
				name := rubyMethodName(m[1], m[2])
				cur.methods = append(cur.methods, name)
			}
			depth++
			continue
		}

		// Other block openers (if/unless/while/until/for/begin/case)
		if rubyOpener.MatchString(raw) {
			depth++
			continue
		}

		// "do" at the end of a line opens a block.
		if rubyDoBlock.MatchString(raw) && !rubyComment.MatchString(raw) {
			depth++
			continue
		}

		// "end" closes the most recent opener.
		if rubyEnd.MatchString(raw) {
			if depth > 0 {
				depth--
			}
			if depth == 0 {
				closeBlock(lineNo)
			}
			continue
		}
	}
	closeBlock(len(lines))

	if len(blocks) == 0 {
		return digest.FileMap{}, false
	}

	var entries []digest.MapEntry
	var symbols []string

	for _, b := range blocks {
		label := rubyBlockLabel(b)
		if len(symbols) < 40 {
			symbols = append(symbols, b.kind+" "+b.name)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(b.startLine, b.endLine),
			Kind:  label,
		})
	}

	summary := rubySummary(blocks, generated)

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
	}, true
}

// rubyMethodName builds a display name for a method, prefixing "self." when
// the receiver group captured it.
func rubyMethodName(receiver, name string) string {
	if receiver != "" {
		return "self." + name
	}
	return name
}

// rubyBlockLabel builds the Kind label for a class or module entry.
// Lists up to 4 method names; adds (+N) for the rest.
func rubyBlockLabel(b *rubyBlock) string {
	label := b.kind + " " + b.name
	if len(b.methods) == 0 {
		return label
	}
	displayed := b.methods
	suffix := ""
	if len(displayed) > 4 {
		displayed = displayed[:4]
		suffix = fmt.Sprintf(" (+%d)", len(b.methods)-4)
	}
	return label + " — " + strings.Join(displayed, ", ") + suffix
}

// rubySummary builds the top-level summary line.
func rubySummary(blocks []*rubyBlock, generated bool) string {
	classCount := 0
	moduleCount := 0
	methodCount := 0
	for _, b := range blocks {
		switch b.kind {
		case "class":
			classCount++
		case "module":
			moduleCount++
		}
		methodCount += len(b.methods)
	}

	var parts []string
	if classCount == 1 {
		parts = append(parts, "1 class")
	} else if classCount > 1 {
		parts = append(parts, fmt.Sprintf("%d classes", classCount))
	}
	if moduleCount == 1 {
		parts = append(parts, "1 module")
	} else if moduleCount > 1 {
		parts = append(parts, fmt.Sprintf("%d modules", moduleCount))
	}
	if methodCount == 1 {
		parts = append(parts, "1 method")
	} else if methodCount > 1 {
		parts = append(parts, fmt.Sprintf("%d methods", methodCount))
	}

	summary := "Ruby — " + strings.Join(parts, ", ")
	if generated {
		summary += " — generated, do not edit directly"
	}
	return summary
}

// hasRubyStructure returns true when at least one class, module, or top-level
// method definition is present.
func hasRubyStructure(lines []string) bool {
	for _, l := range lines {
		if rubyClassMod.MatchString(l) || rubyDef.MatchString(l) {
			return true
		}
	}
	return false
}
