package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	rsModuleDoc = regexp.MustCompile(`^//[!/]\s*(.+)`)  // //! or /// at top of file

	rsPubFn    = regexp.MustCompile(`^pub(?:\([^)]*\))?\s+(?:async\s+)?fn\s+(\w+)`)
	rsFn       = regexp.MustCompile(`^(?:async\s+)?fn\s+(\w+)`)
	rsPubStruct = regexp.MustCompile(`^pub(?:\([^)]*\))?\s+struct\s+(\w+)`)
	rsStruct   = regexp.MustCompile(`^struct\s+(\w+)`)
	rsPubEnum  = regexp.MustCompile(`^pub(?:\([^)]*\))?\s+enum\s+(\w+)`)
	rsEnum     = regexp.MustCompile(`^enum\s+(\w+)`)
	rsPubTrait = regexp.MustCompile(`^pub(?:\([^)]*\))?\s+trait\s+(\w+)`)
	rsTrait    = regexp.MustCompile(`^trait\s+(\w+)`)
	rsImpl     = regexp.MustCompile(`^impl(?:<[^>]*>)?\s+(?:\w+\s+for\s+)?(\w+)`)
	rsMod      = regexp.MustCompile(`^(?:pub(?:\([^)]*\))?\s+)?mod\s+(\w+)`)
	rsUse      = regexp.MustCompile(`^use\s+`)
	rsExternCrate = regexp.MustCompile(`^extern\s+crate\s+`)
	rsAttr     = regexp.MustCompile(`^#\[`)
	rsGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|Code generated|autogenerated`)
)

// parseRustFile builds a FileMap from a Rust source file using regex-based
// line scanning. It extracts top-level items (fn, struct, enum, trait, impl,
// mod) and their visibility, producing a structural digest without a worker
// call. Generated files, test modules, and files with no recognizable Rust
// structure fall through to the worker.
func parseRustFile(src, _ string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasRustStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no recognizable Rust structure")
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if rsGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	// Module-level doc comment: collect //! lines from the top.
	moduleSummary := extractRustModuleDoc(lines)

	type section struct {
		start int
		end   int
		kind  string
		name  string
		pub   bool
	}

	var sections []section
	var symbols []string
	seenSymbols := map[string]bool{}

	addSymbol := func(name string, pub bool) {
		if name == "" || seenSymbols[name] || len(symbols) >= 40 {
			return
		}
		if pub {
			symbols = append(symbols, name)
			seenSymbols[name] = true
		}
	}

	depth := 0
	inDecl := false
	declStart := 0
	declKind := ""
	declName := ""
	declPub := false
	pendingAttr := 0
	useStart, useEnd := 0, 0

	closeDecl := func(endLine int) {
		if inDecl && declStart > 0 {
			sections = append(sections, section{declStart, endLine, declKind, declName, declPub})
		}
		inDecl = false
		declStart = 0
		declKind = ""
		declName = ""
		declPub = false
	}

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" || strings.HasPrefix(trimmed, "//") {
			if inDecl {
				opened, closed := countBraces(raw)
				depth += opened - closed
				if depth < 0 {
					depth = 0
				}
				if depth == 0 {
					closeDecl(lineNo)
				}
			}
			continue
		}

		// Attribute lines (#[...]) — mark start line for next decl.
		if rsAttr.MatchString(trimmed) {
			if pendingAttr == 0 {
				pendingAttr = lineNo
			}
			if inDecl {
				opened, closed := countBraces(raw)
				depth += opened - closed
				if depth < 0 {
					depth = 0
				}
				if depth == 0 {
					closeDecl(lineNo)
				}
			}
			continue
		}

		if inDecl {
			opened, closed := countBraces(raw)
			depth += opened - closed
			if depth < 0 {
				depth = 0
			}
			if depth == 0 {
				closeDecl(lineNo)
			}
			continue
		}

		// use / extern crate — group into a "uses" block.
		if rsUse.MatchString(trimmed) || rsExternCrate.MatchString(trimmed) {
			if useStart == 0 {
				useStart = lineNo
			}
			useEnd = lineNo
			pendingAttr = 0
			continue
		}

		startLine := lineNo
		if pendingAttr > 0 {
			startLine = pendingAttr
			pendingAttr = 0
		}

		match := func(re *regexp.Regexp) (string, bool) {
			m := re.FindStringSubmatch(trimmed)
			if m != nil {
				return m[1], true
			}
			return "", false
		}

		var name string
		var ok bool
		var kind string
		var pub bool

		switch {
		case func() bool { name, ok = match(rsPubFn); return ok }():
			kind, pub = "pub fn "+name, true
		case func() bool { name, ok = match(rsFn); return ok }():
			kind = "fn " + name
		case func() bool { name, ok = match(rsPubStruct); return ok }():
			kind, pub = "pub struct "+name, true
		case func() bool { name, ok = match(rsStruct); return ok }():
			kind = "struct " + name
		case func() bool { name, ok = match(rsPubEnum); return ok }():
			kind, pub = "pub enum "+name, true
		case func() bool { name, ok = match(rsEnum); return ok }():
			kind = "enum " + name
		case func() bool { name, ok = match(rsPubTrait); return ok }():
			kind, pub = "pub trait "+name, true
		case func() bool { name, ok = match(rsTrait); return ok }():
			kind = "trait " + name
		case func() bool { name, ok = match(rsImpl); return ok }():
			kind = "impl " + name
		case func() bool { name, ok = match(rsMod); return ok }():
			kind = "mod " + name
			if strings.Contains(trimmed, "pub") {
				pub = true
				kind = "pub mod " + name
			}
		default:
			continue
		}

		addSymbol(name, pub)
		opened, closed := countBraces(raw)
		depth = opened - closed
		if depth <= 0 {
			// Single-line item (e.g. `mod foo;`).
			sections = append(sections, section{startLine, lineNo, kind, name, pub})
			depth = 0
		} else {
			inDecl = true
			declStart = startLine
			declKind = kind
			declName = name
			declPub = pub
		}
	}

	if inDecl {
		closeDecl(len(lines))
	}

	var entries []digest.MapEntry

	if useStart > 0 {
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(useStart, useEnd),
			Kind:  "use declarations",
		})
	}

	for _, s := range sections {
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(s.start, s.end),
			Kind:  s.kind,
		})
	}

	if len(entries) == 0 {
		entries = []digest.MapEntry{{Lines: lineRange(1, len(lines)), Kind: "module body"}}
	}

	// Summary.
	summary := moduleSummary
	if summary == "" {
		summary = "Rust module"
	}
	if generated {
		summary += " — generated file, do not edit directly"
	}

	var notes string
	if generated {
		notes = "generated file — edit the generator, not this file"
	}

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
		Notes:   notes,
	}, nil
}

// hasRustStructure returns true when the source has at least one recognizable
// Rust top-level construct.
func hasRustStructure(lines []string) bool {
	for _, l := range lines {
		t := strings.TrimSpace(l)
		if rsUse.MatchString(t) || rsPubFn.MatchString(t) || rsFn.MatchString(t) ||
			rsPubStruct.MatchString(t) || rsStruct.MatchString(t) ||
			rsPubEnum.MatchString(t) || rsEnum.MatchString(t) ||
			rsPubTrait.MatchString(t) || rsTrait.MatchString(t) ||
			rsImpl.MatchString(t) || rsMod.MatchString(t) {
			return true
		}
	}
	return false
}

// extractRustModuleDoc collects the text of leading //! (inner doc comment)
// lines. These are Rust's conventional module-level documentation.
func extractRustModuleDoc(lines []string) string {
	var parts []string
	for _, l := range lines {
		t := strings.TrimSpace(l)
		if m := rsModuleDoc.FindStringSubmatch(t); m != nil && strings.HasPrefix(t, "//!") {
			if text := strings.TrimSpace(m[1]); text != "" {
				parts = append(parts, text)
				if len(parts) >= 2 {
					break
				}
			}
		} else if t == "" || strings.HasPrefix(t, "//") {
			continue
		} else {
			break
		}
	}
	return strings.Join(parts, " ")
}
