package filemap

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// shellFuncDef matches POSIX and bash function definitions:
	//   function name { ... }     (bash-style)
	//   name() { ... }            (POSIX-style)
	//   name () { ... }           (POSIX with space)
	shellFuncDef = regexp.MustCompile(`^(?:function\s+([A-Za-z_][A-Za-z0-9_:.\-]*)(?:\s*\(\))?\s*\{?|([A-Za-z_][A-Za-z0-9_:.\-]*)\s*\(\)\s*\{?)`)
	// shellComment is a shell comment line.
	shellComment = regexp.MustCompile(`^\s*#`)
	// shellGenerated marks generated shell scripts.
	shellGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|autogenerated`)
	// shellShebang matches a shebang line.
	shellShebang = regexp.MustCompile(`^#!`)
	// shellSource matches a . or source statement.
	shellSource = regexp.MustCompile(`^(?:\.|source)\s+(\S+)`)
	// shellExport matches a variable export or declaration.
	shellExport = regexp.MustCompile(`^(?:export|declare|typeset|local)\s+([A-Za-z_][A-Za-z0-9_]*)`)
)

// shellFunc tracks one function block while parsing.
type shellFunc struct {
	name      string
	startLine int
	endLine   int
}

// parseShellFile builds a FileMap from a shell script. Functions are the
// primary structural unit; each gets one map entry spanning from its
// definition line to the closing brace (or the next function, whichever
// comes first). Top-level source/. calls and exported variables are
// collected as Symbols. Scripts with no functions produce a single summary
// entry instead.
func parseShellFile(src, filePath string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasShellStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no shell structure found")
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if shellGenerated.MatchString(l) {
			generated = true
			break
		}
		if shellShebang.MatchString(l) {
			break // shebang on line 1 is expected; generation marker comes later
		}
	}

	// Collect sourced files and exported variables for the symbol list.
	var sources []string
	var exports []string
	sourceSeen := map[string]bool{}
	exportSeen := map[string]bool{}

	var funcs []*shellFunc
	var cur *shellFunc
	depth := 0 // brace depth inside the current function

	closeFunc := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			funcs = append(funcs, cur)
			cur = nil
			depth = 0
		}
	}

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" {
			continue
		}

		// Count brace open/close to track function body extent.
		if cur != nil {
			for _, ch := range trimmed {
				if ch == '{' {
					depth++
				} else if ch == '}' {
					depth--
				}
			}
			if depth <= 0 {
				closeFunc(lineNo)
				continue
			}
		}

		if shellComment.MatchString(raw) {
			continue
		}

		if m := shellFuncDef.FindStringSubmatch(trimmed); m != nil {
			closeFunc(lineNo - 1)
			name := m[1]
			if name == "" {
				name = m[2]
			}
			cur = &shellFunc{
				name:      name,
				startLine: lineNo,
			}
			// Count opening brace on the same line (common: `fn() {`).
			depth = 0
			for _, ch := range trimmed {
				if ch == '{' {
					depth++
				} else if ch == '}' {
					depth--
				}
			}
			if depth <= 0 && strings.Contains(trimmed, "{") {
				// Single-line function with closing brace on same line.
				closeFunc(lineNo)
			}
			continue
		}

		if cur == nil {
			// Top-level statements.
			if m := shellSource.FindStringSubmatch(trimmed); m != nil {
				if !sourceSeen[m[1]] && len(sources) < 10 {
					sources = append(sources, m[1])
					sourceSeen[m[1]] = true
				}
			}
			if m := shellExport.FindStringSubmatch(trimmed); m != nil {
				if !exportSeen[m[1]] && len(exports) < 10 {
					exports = append(exports, m[1])
					exportSeen[m[1]] = true
				}
			}
		}
	}
	closeFunc(len(lines))

	var entries []digest.MapEntry
	var symbols []string

	for _, f := range funcs {
		if len(symbols) < 40 {
			symbols = append(symbols, f.name)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(f.startLine, f.endLine),
			Kind:  f.name,
		})
	}

	// Supplement symbol list with source files and notable exports.
	for _, s := range sources {
		if len(symbols) < 40 {
			symbols = append(symbols, "source "+s)
		}
	}

	summary := shellSummary(filePath, len(funcs), len(lines), generated)

	var notes string
	if len(sources) > 0 {
		notes = fmt.Sprintf("sources: %s", strings.Join(sources, ", "))
	}

	// If no functions were found, produce a single summary entry for the whole
	// file (setup scripts, sourced libraries that only export variables).
	if len(entries) == 0 {
		entries = []digest.MapEntry{{
			Lines: lineRange(1, len(lines)),
			Kind:  "script body",
		}}
		for _, e := range exports {
			if len(symbols) < 40 {
				symbols = append(symbols, e)
			}
		}
	}

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
		Notes:   notes,
	}, nil
}

// shellSummary builds the top-level summary line.
func shellSummary(filePath string, funcCount, lineCount int, generated bool) string {
	base := strings.ToLower(filepath.Base(filePath))

	var kind string
	switch {
	case strings.HasSuffix(base, ".zsh") || base == ".zshrc" || base == ".zshenv" || base == ".zprofile":
		kind = "Zsh script"
	case strings.HasSuffix(base, ".bash") || base == ".bashrc" || base == ".bash_profile" || base == ".bash_logout":
		kind = "Bash script"
	case strings.HasSuffix(base, ".fish"):
		kind = "Fish script"
	default:
		kind = "Shell script"
	}

	summary := fmt.Sprintf("%s — %d line(s)", kind, lineCount)
	if funcCount > 0 {
		summary += fmt.Sprintf(", %d function(s)", funcCount)
	}
	if generated {
		summary += " — generated, do not edit directly"
	}
	return summary
}

// hasShellStructure returns true when the file looks like a shell script:
// a shebang referencing a shell interpreter, or at least one function
// definition or shell-ism.
func hasShellStructure(lines []string) bool {
	if len(lines) == 0 {
		return false
	}

	// Shebang referencing a shell.
	if shellShebang.MatchString(lines[0]) {
		lower := strings.ToLower(lines[0])
		for _, sh := range []string{"sh", "bash", "zsh", "fish", "dash", "ksh", "ash"} {
			if strings.Contains(lower, sh) {
				return true
			}
		}
	}

	// A function definition anywhere in the file.
	for _, l := range lines {
		if shellFuncDef.MatchString(strings.TrimSpace(l)) {
			return true
		}
	}

	return false
}
