package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// sqlCreateTable matches CREATE [TEMP|UNLOGGED] TABLE [IF NOT EXISTS] name
	sqlCreateTable = regexp.MustCompile(
		`(?i)^\s*CREATE\s+(?:TEMP(?:ORARY)?\s+|UNLOGGED\s+)?TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?` +
			`"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlCreateIndex matches CREATE [UNIQUE] INDEX [CONCURRENTLY] [IF NOT EXISTS] name ON table
	sqlCreateIndex = regexp.MustCompile(
		`(?i)^\s*CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?` +
			`"?([A-Za-z_][A-Za-z0-9_."]*)"?\s+ON\s+"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlCreateView matches CREATE [OR REPLACE] [TEMP] VIEW [IF NOT EXISTS] name
	sqlCreateView = regexp.MustCompile(
		`(?i)^\s*CREATE\s+(?:OR\s+REPLACE\s+)?(?:TEMP(?:ORARY)?\s+)?VIEW\s+(?:IF\s+NOT\s+EXISTS\s+)?` +
			`"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlCreateFunc matches CREATE [OR REPLACE] FUNCTION name
	sqlCreateFunc = regexp.MustCompile(
		`(?i)^\s*CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlCreateProc matches CREATE [OR REPLACE] PROCEDURE name
	sqlCreateProc = regexp.MustCompile(
		`(?i)^\s*CREATE\s+(?:OR\s+REPLACE\s+)?PROCEDURE\s+"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlCreateTrigger matches CREATE [CONSTRAINT] TRIGGER name
	sqlCreateTrigger = regexp.MustCompile(
		`(?i)^\s*CREATE\s+(?:CONSTRAINT\s+)?TRIGGER\s+"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlCreateType matches CREATE TYPE name
	sqlCreateType = regexp.MustCompile(
		`(?i)^\s*CREATE\s+TYPE\s+"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlCreateSequence matches CREATE [TEMP] SEQUENCE [IF NOT EXISTS] name
	sqlCreateSequence = regexp.MustCompile(
		`(?i)^\s*CREATE\s+(?:TEMP(?:ORARY)?\s+)?SEQUENCE\s+(?:IF\s+NOT\s+EXISTS\s+)?` +
			`"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlAlterTable matches ALTER TABLE [IF EXISTS] [ONLY] name
	sqlAlterTable = regexp.MustCompile(
		`(?i)^\s*ALTER\s+TABLE\s+(?:IF\s+EXISTS\s+)?(?:ONLY\s+)?"?([A-Za-z_][A-Za-z0-9_."]*)"?`)
	// sqlComment matches SQL line comments.
	sqlComment = regexp.MustCompile(`^\s*--`)
	// sqlBlockComment matches the start of a /* block comment.
	sqlBlockComment = regexp.MustCompile(`^\s*/\*`)
	// sqlGenerated marks generated SQL files.
	sqlGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|autogenerated|pg_dump|mysqldump|This file is auto-generated`)
	// sqlDollarQuote matches a PostgreSQL dollar-quoting delimiter: $$ or $tag$
	sqlDollarQuote = regexp.MustCompile(`\$([A-Za-z_]*)\$`)
)

// sqlStmt records one DDL statement while parsing.
type sqlStmt struct {
	kind      string // "table", "index", "view", "function", "procedure", "trigger", "type", "sequence", "alter"
	name      string
	extra     string // e.g. "on users" for an index
	startLine int
	endLine   int
}

// parseSQLFile builds a FileMap from a SQL file. Each top-level DDL statement
// becomes one map entry. The Kind label names the object type and identifier.
//
// Statement boundaries are tracked by counting semicolons, with special
// handling for PostgreSQL dollar-quoted function bodies ($$...$$) which can
// contain semicolons that are not statement terminators.
func parseSQLFile(src, _ string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasSQLStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no SQL DDL statements found")
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if sqlGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	var stmts []*sqlStmt
	var cur *sqlStmt
	inBlockComment := false
	dollarMarker := "" // non-empty when inside a PostgreSQL dollar-quoted body

	closeStmt := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			stmts = append(stmts, cur)
			cur = nil
		}
	}

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" {
			continue
		}

		// Dollar-quote body: skip until the closing marker.
		if dollarMarker != "" {
			if strings.Contains(raw, dollarMarker) {
				dollarMarker = ""
				// The closing marker line may also end the statement.
				if strings.HasSuffix(strings.TrimSpace(raw), ";") {
					closeStmt(lineNo)
				}
			}
			continue
		}

		// Block comment tracking.
		if inBlockComment {
			if strings.Contains(raw, "*/") {
				inBlockComment = false
			}
			continue
		}
		if sqlBlockComment.MatchString(raw) {
			if !strings.Contains(raw, "*/") {
				inBlockComment = true
			}
			continue
		}
		if sqlComment.MatchString(raw) {
			continue
		}

		// Check for PostgreSQL dollar-quote opening inside the current statement.
		if cur != nil {
			if m := sqlDollarQuote.FindStringSubmatch(raw); m != nil {
				// Only enter dollar-quote mode if this is an opening delimiter
				// (not the same marker closing itself on the same line).
				marker := "$" + m[1] + "$"
				count := strings.Count(raw, marker)
				if count == 1 {
					// Single occurrence: opening a dollar-quoted block.
					dollarMarker = marker
					continue
				}
				// Two occurrences on the same line: open and close on same line —
				// fall through to normal semicolon check.
			}
		}

		// Statement end: a line (or end of line) with a bare semicolon.
		if cur != nil && sqlLineEndsStat(raw) {
			closeStmt(lineNo)
			continue
		}

		if cur != nil {
			continue // still inside the current statement body
		}

		// Looking for a new DDL statement.
		if s := matchSQLStmt(trimmed, lineNo); s != nil {
			cur = s
			// A dollar-quote delimiter may appear on the same line that opens
			// the statement, e.g. "CREATE FUNCTION foo() RETURNS trigger AS $$".
			// Check here before the semicolon test so we don't close the
			// statement on a semicolon inside the body.
			if m := sqlDollarQuote.FindStringSubmatch(raw); m != nil {
				marker := "$" + m[1] + "$"
				if strings.Count(raw, marker) == 1 {
					dollarMarker = marker
					continue
				}
			}
			// Single-line statement: e.g. "CREATE SEQUENCE foo;"
			if sqlLineEndsStat(raw) {
				closeStmt(lineNo)
			}
		}
	}
	closeStmt(len(lines))

	if len(stmts) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: no SQL DDL statements found")
	}

	var entries []digest.MapEntry
	var symbols []string

	for _, s := range stmts {
		label := sqlStmtLabel(s)
		if len(symbols) < 40 {
			symbols = append(symbols, label)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(s.startLine, s.endLine),
			Kind:  label,
		})
	}

	summary := sqlSummary(stmts, generated)

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
	}, nil
}

// matchSQLStmt tries to match a DDL keyword at the start of line and returns
// a new sqlStmt or nil if the line is not a recognized DDL opener.
func matchSQLStmt(trimmed string, lineNo int) *sqlStmt {
	if m := sqlCreateTable.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "table", name: sqlUnquote(m[1]), startLine: lineNo}
	}
	if m := sqlCreateIndex.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "index", name: sqlUnquote(m[1]), extra: "on " + sqlUnquote(m[2]), startLine: lineNo}
	}
	if m := sqlCreateView.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "view", name: sqlUnquote(m[1]), startLine: lineNo}
	}
	if m := sqlCreateFunc.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "function", name: sqlUnquote(m[1]), startLine: lineNo}
	}
	if m := sqlCreateProc.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "procedure", name: sqlUnquote(m[1]), startLine: lineNo}
	}
	if m := sqlCreateTrigger.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "trigger", name: sqlUnquote(m[1]), startLine: lineNo}
	}
	if m := sqlCreateType.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "type", name: sqlUnquote(m[1]), startLine: lineNo}
	}
	if m := sqlCreateSequence.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "sequence", name: sqlUnquote(m[1]), startLine: lineNo}
	}
	if m := sqlAlterTable.FindStringSubmatch(trimmed); m != nil {
		return &sqlStmt{kind: "alter", name: sqlUnquote(m[1]), startLine: lineNo}
	}
	return nil
}

// sqlLineEndsStat reports whether line ends a SQL statement (ends with ;
// after stripping comments and whitespace).
func sqlLineEndsStat(raw string) bool {
	// Strip trailing line comment first.
	if idx := strings.Index(raw, "--"); idx >= 0 {
		raw = raw[:idx]
	}
	return strings.HasSuffix(strings.TrimSpace(raw), ";")
}

// sqlUnquote strips double-quote wrapping from a SQL identifier if present.
func sqlUnquote(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, `"`) && strings.HasSuffix(s, `"`) {
		return s[1 : len(s)-1]
	}
	return s
}

// sqlStmtLabel builds the display label for one SQL statement.
func sqlStmtLabel(s *sqlStmt) string {
	switch s.kind {
	case "index":
		if s.extra != "" {
			return "index " + s.name + " " + s.extra
		}
	case "alter":
		return "alter table " + s.name
	}
	return s.kind + " " + s.name
}

// sqlSummary builds the top-level summary line.
func sqlSummary(stmts []*sqlStmt, generated bool) string {
	counts := map[string]int{}
	for _, s := range stmts {
		counts[s.kind]++
	}

	ordered := []string{"table", "view", "index", "function", "procedure", "trigger", "type", "sequence", "alter"}
	var parts []string
	for _, t := range ordered {
		n := counts[t]
		if n == 0 {
			continue
		}
		noun := t
		if t == "alter" {
			noun = "alter table"
		}
		if n == 1 {
			parts = append(parts, "1 "+noun)
		} else {
			parts = append(parts, fmt.Sprintf("%d %ss", n, noun))
		}
	}

	prefix := "SQL"
	if counts["table"] > 0 && counts["alter"] == 0 && counts["index"] == 0 {
		prefix = "SQL schema"
	} else if counts["alter"] > 0 && counts["table"] == 0 {
		prefix = "SQL migration"
	}

	summary := prefix + " — " + strings.Join(parts, ", ")
	if generated {
		summary += " — generated, do not edit directly"
	}
	return summary
}

// hasSQLStructure returns true when at least one recognized DDL statement
// is present.
func hasSQLStructure(lines []string) bool {
	for _, l := range lines {
		t := strings.TrimSpace(l)
		if matchSQLStmt(t, 0) != nil {
			return true
		}
	}
	return false
}
