package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// swiftTopBlock matches a top-level Swift type declaration.
	// Access modifiers are consumed but not captured; type-shaping modifiers
	// (final, open) and the keyword land in group 1; name in group 2.
	// Groups: (1) kind phrase, (2) name
	swiftTopBlock = regexp.MustCompile(
		`^\s*(?:(?:public|private|internal|fileprivate|open)\s+)*` +
			`((?:(?:final|open)\s+)*` +
			`(?:class|struct|enum|protocol|actor|extension))\s+([A-Za-z_][A-Za-z0-9_]*)`)
	// swiftFunc matches a function declaration at any depth.
	// Groups: (1) name
	swiftFunc = regexp.MustCompile(
		`^\s*(?:(?:@\w+(?:\([^)]*\))?\s+)*)` + // attributes (@IBAction etc.)
			`(?:(?:public|private|internal|fileprivate|open|override|static|class|mutating|nonmutating|dynamic|final|required|convenience|nonisolated)\s+)*` +
			`func\s+([A-Za-z_][A-Za-z0-9_]*)`)
	// swiftComment matches Swift single-line comments.
	swiftComment = regexp.MustCompile(`^\s*//`)
	// swiftBlockComment matches the start of a /* ... */ comment.
	swiftBlockCommentOpen = regexp.MustCompile(`^\s*/\*`)
	// swiftGenerated detects generated Swift files.
	swiftGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|auto.?generated|This file was automatically generated|Generated by|swiftgen|sourcery`)
	// swiftInit matches init/deinit declarations (counted as functions).
	swiftInit = regexp.MustCompile(`^\s*(?:(?:public|private|internal|fileprivate|open|override|required|convenience)\s+)*(?:init|deinit)\s*[({?!]`)
)

// swiftBlock tracks one top-level Swift type declaration while parsing.
type swiftBlock struct {
	kind      string
	name      string
	startLine int
	endLine   int
	funcs     []string
}

// parseSwiftFile builds a FileMap from a Swift source file. Each top-level
// type declaration becomes one map entry; its Kind label lists function names
// (up to 4, with +N overflow).
func parseSwiftFile(src, _ string) (digest.FileMap, bool) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, false
	}
	if !hasSwiftStructure(lines) {
		return digest.FileMap{}, false
	}

	generated := false
	for _, l := range lines[:min(len(lines), 10)] {
		if swiftGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	var blocks []*swiftBlock
	var cur *swiftBlock
	var pendingBlock *swiftBlock // waiting for opening "{" (split header)
	depth := 0
	inBlockComment := false
	inTripleQuote := false

	closeBlock := func(endLine int) {
		if cur != nil {
			cur.endLine = endLine
			blocks = append(blocks, cur)
			cur = nil
		}
	}

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" {
			continue
		}

		// Triple-quoted string tracking ("""...""" spans multiple lines).
		tripleCount := strings.Count(trimmed, `"""`)
		if inTripleQuote {
			if tripleCount%2 == 1 {
				inTripleQuote = false
			}
			continue
		}
		if tripleCount%2 == 1 {
			inTripleQuote = true
			continue
		}

		// Block comment state is carried inside swiftNetBraces.
		startedInBC := inBlockComment

		// Waiting for the opening "{" of a split type header.
		if pendingBlock != nil {
			d := swiftNetBraces(raw, &inBlockComment)
			if d > 0 {
				cur = pendingBlock
				depth = d
				pendingBlock = nil
			} else if d < 0 {
				pendingBlock = nil
			}
			continue
		}

		if cur != nil {
			// Collect funcs at depth 1 BEFORE updating depth.
			if !startedInBC && depth == 1 {
				if swiftInit.MatchString(raw) {
					cur.funcs = append(cur.funcs, "init")
				} else if m := swiftFunc.FindStringSubmatch(trimmed); m != nil {
					cur.funcs = append(cur.funcs, m[1])
				}
			}
			depth += swiftNetBraces(raw, &inBlockComment)
			if depth <= 0 {
				closeBlock(lineNo)
				depth = 0
			}
			continue
		}

		// Top level.
		if startedInBC {
			swiftNetBraces(raw, &inBlockComment)
			continue
		}
		if swiftComment.MatchString(raw) {
			continue
		}

		if m := swiftTopBlock.FindStringSubmatch(trimmed); m != nil {
			kind := strings.TrimSpace(m[1])
			b := &swiftBlock{kind: kind, name: m[2], startLine: lineNo}
			d := swiftNetBraces(raw, &inBlockComment)
			if d > 0 {
				cur = b
				depth = d
			} else {
				pendingBlock = b
			}
			continue
		}
	}
	closeBlock(len(lines))

	if len(blocks) == 0 {
		return digest.FileMap{}, false
	}

	var entries []digest.MapEntry
	var symbols []string
	for _, b := range blocks {
		label := swiftBlockLabel(b)
		if len(symbols) < 40 {
			symbols = append(symbols, b.kind+" "+b.name)
		}
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(b.startLine, b.endLine),
			Kind:  label,
		})
	}

	return digest.FileMap{
		Summary: swiftSummary(blocks, generated),
		Map:     entries,
		Symbols: symbols,
	}, true
}

// swiftNetBraces counts net brace depth for a Swift line, ignoring braces
// inside double-quoted strings, character literals, // comments, and /* */
// block comments. inBC carries block-comment state across lines.
func swiftNetBraces(line string, inBC *bool) int {
	depth := 0
	inStr := false
	for i := 0; i < len(line); i++ {
		ch := line[i]
		if *inBC {
			if ch == '*' && i+1 < len(line) && line[i+1] == '/' {
				*inBC = false
				i++
			}
			continue
		}
		if inStr {
			if ch == '\\' {
				i++
				continue
			}
			if ch == '"' {
				inStr = false
			}
			continue
		}
		switch ch {
		case '"':
			inStr = true
		case '\'':
			// Swift character literals use String, not char; single-quote is
			// used in string interpolation contexts but not as a standalone
			// character literal. Skip as a no-op here.
		case '/':
			if i+1 < len(line) && line[i+1] == '/' {
				return depth
			}
			if i+1 < len(line) && line[i+1] == '*' {
				*inBC = true
				i++
			}
		case '{':
			depth++
		case '}':
			depth--
		}
	}
	return depth
}

// swiftBlockLabel builds the Kind label for a Swift block entry.
func swiftBlockLabel(b *swiftBlock) string {
	label := b.kind + " " + b.name
	if len(b.funcs) == 0 {
		return label
	}
	displayed := b.funcs
	suffix := ""
	if len(displayed) > 4 {
		displayed = displayed[:4]
		suffix = fmt.Sprintf(" (+%d)", len(b.funcs)-4)
	}
	return label + " — " + strings.Join(displayed, ", ") + suffix
}

// swiftSummary builds the top-level summary line.
func swiftSummary(blocks []*swiftBlock, generated bool) string {
	counts := map[string]int{}
	funcCount := 0
	for _, b := range blocks {
		counts[b.kind]++
		funcCount += len(b.funcs)
	}

	ordered := []string{"class", "final class", "open class", "struct", "enum",
		"protocol", "actor", "extension"}
	var parts []string
	for _, k := range ordered {
		n := counts[k]
		if n == 0 {
			continue
		}
		if n == 1 {
			parts = append(parts, "1 "+k)
		} else {
			words := strings.Fields(k)
			words[len(words)-1] += "s"
			parts = append(parts, fmt.Sprintf("%d %s", n, strings.Join(words, " ")))
		}
	}
	if funcCount == 1 {
		parts = append(parts, "1 func")
	} else if funcCount > 1 {
		parts = append(parts, fmt.Sprintf("%d funcs", funcCount))
	}

	summary := "Swift — " + strings.Join(parts, ", ")
	if generated {
		summary += " — generated, do not edit directly"
	}
	return summary
}

// hasSwiftStructure returns true when at least one class/struct/enum/protocol/
// actor/extension declaration is present.
func hasSwiftStructure(lines []string) bool {
	for _, l := range lines {
		if swiftTopBlock.MatchString(l) {
			return true
		}
	}
	return false
}
