package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	// tomlTableHeader matches [section] or [section.sub] — standard table.
	tomlTableHeader = regexp.MustCompile(`^\[([^\[\]]+)\]$`)
	// tomlArrayHeader matches [[array-of-tables]] — used in Cargo [[bin]], [[test]], etc.
	tomlArrayHeader = regexp.MustCompile(`^\[\[([^\[\]]+)\]\]$`)
	// tomlKeyValue matches a bare or quoted key assignment: key = ... or "key" = ...
	tomlKeyValue = regexp.MustCompile(`^([A-Za-z0-9_\-."]+)\s*=`)
	// tomlComment matches a whole-line comment.
	tomlComment = regexp.MustCompile(`^\s*#`)
	// tomlGenerated matches generated-file markers in the first few lines.
	tomlGenerated = regexp.MustCompile(`@generated|DO NOT EDIT|autogenerated|Code generated`)
)

// tomlSection tracks one table block while parsing.
type tomlSection struct {
	header    string   // e.g. "package", "dependencies", "bin"
	isArray   bool     // true for [[...]] headers
	startLine int
	endLine   int
	keys      []string // up to 12 key names
}

// parseTOMLFile builds a FileMap from a TOML source file using a line scanner.
//
// TOML is section-oriented: each [table] header starts a new block, and
// key = value lines belong to the most recently opened section. This maps
// naturally to digest.MapEntry per section. Well-known files (Cargo.toml,
// pyproject.toml) get specific summaries.
func parseTOMLFile(src, filePath string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasTOMLStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no recognizable TOML structure")
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if tomlGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	// rootSection holds key-value pairs that appear before any [table] header.
	rootSection := &tomlSection{header: "__root__", startLine: 1}
	var sections []*tomlSection
	current := rootSection

	closeSection := func(endLine int) {
		current.endLine = endLine
		sections = append(sections, current)
	}

	for i, raw := range lines {
		lineNo := i + 1
		trimmed := strings.TrimSpace(raw)

		if trimmed == "" || tomlComment.MatchString(raw) {
			continue
		}

		if m := tomlArrayHeader.FindStringSubmatch(trimmed); m != nil {
			closeSection(lineNo - 1)
			current = &tomlSection{header: m[1], isArray: true, startLine: lineNo}
			continue
		}

		if m := tomlTableHeader.FindStringSubmatch(trimmed); m != nil {
			closeSection(lineNo - 1)
			current = &tomlSection{header: m[1], startLine: lineNo}
			continue
		}

		if m := tomlKeyValue.FindStringSubmatch(trimmed); m != nil {
			key := strings.Trim(m[1], `"`)
			if len(current.keys) < 12 {
				current.keys = append(current.keys, key)
			}
		}
	}
	closeSection(len(lines))

	// Filter out the empty root section when there are named sections to show.
	var filtered []*tomlSection
	for _, s := range sections {
		if s.header == "__root__" && len(s.keys) == 0 && len(sections) > 1 {
			continue
		}
		filtered = append(filtered, s)
	}

	if len(filtered) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: no sections found")
	}

	var entries []digest.MapEntry
	var symbols []string
	// symbolSeen deduplicates the symbols list for repeated [[array-of-tables]]
	// headers (e.g. multiple [[bin]] blocks). Each block keeps its own line
	// range in the map — merging ranges would cause unrelated sections in
	// between to appear as part of [[bin]].
	symbolSeen := map[string]bool{}

	for _, s := range filtered {
		if s.header == "__root__" {
			// Root keys become individual symbols without a section label.
			for _, k := range s.keys {
				if len(symbols) < 40 {
					symbols = append(symbols, k)
				}
			}
			if len(s.keys) > 0 {
				entries = append(entries, digest.MapEntry{
					Lines: lineRange(s.startLine, s.endLine),
					Kind:  tomlRootKindLabel(s.keys),
				})
			}
		} else {
			name := tomlSectionDisplayName(s)
			if len(symbols) < 40 && !symbolSeen[name] {
				symbols = append(symbols, name)
				symbolSeen[name] = true
			}
			entries = append(entries, digest.MapEntry{
				Lines: lineRange(s.startLine, s.endLine),
				Kind:  tomlSectionKindLabel(s),
			})
		}
	}

	summary := describeTOMLSummary(filtered, filePath)
	if generated {
		summary += " — generated, do not edit directly"
	}

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
	}, nil
}

// tomlSectionDisplayName returns the name used in the symbols list.
func tomlSectionDisplayName(s *tomlSection) string {
	if s.isArray {
		return "[[" + s.header + "]]"
	}
	return "[" + s.header + "]"
}

// tomlSectionKindLabel builds the Kind field for a non-root section.
func tomlSectionKindLabel(s *tomlSection) string {
	prefix := "[" + s.header + "]"
	if s.isArray {
		prefix = "[[" + s.header + "]]"
	}
	if len(s.keys) == 0 {
		return prefix
	}
	shown := s.keys
	extra := 0
	if len(shown) > 6 {
		shown = shown[:6]
		extra = len(s.keys) - 6
	}
	label := prefix + " — " + strings.Join(shown, ", ")
	if extra > 0 {
		label += fmt.Sprintf(" (+%d more)", extra)
	}
	return label
}

// tomlRootKindLabel describes the unlabeled root key-value block.
func tomlRootKindLabel(keys []string) string {
	shown := keys
	if len(shown) > 6 {
		shown = shown[:6]
	}
	return "root: " + strings.Join(shown, ", ")
}

// describeTOMLSummary infers the file type from its name and section headers.
func describeTOMLSummary(sections []*tomlSection, filePath string) string {
	base := strings.ToLower(filePath)
	if i := strings.LastIndexByte(base, '/'); i >= 0 {
		base = base[i+1:]
	}

	// Well-known filenames.
	switch base {
	case "cargo.toml":
		return "Cargo package manifest"
	case "pyproject.toml":
		return "Python project config (pyproject.toml)"
	case "poetry.toml":
		return "Poetry config"
	}

	// Infer from section headers.
	sectionSet := map[string]bool{}
	for _, s := range sections {
		sectionSet[s.header] = true
		// Also check first component: "dependencies" from "dependencies.foo"
		parts := strings.SplitN(s.header, ".", 2)
		sectionSet[parts[0]] = true
	}

	switch {
	case sectionSet["package"] && (sectionSet["dependencies"] || sectionSet["dev-dependencies"]):
		return "Cargo package manifest"
	case sectionSet["tool"] && sectionSet["build-system"]:
		return "Python project config (pyproject.toml)"
	case sectionSet["tool.poetry"]:
		return "Poetry project config"
	}

	return fmt.Sprintf("TOML config — %d section(s)", len(sections))
}

// hasTOMLStructure returns true if the source contains at least one TOML
// key-value pair or table header, rejecting empty files and non-TOML text.
func hasTOMLStructure(lines []string) bool {
	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if tomlTableHeader.MatchString(trimmed) || tomlArrayHeader.MatchString(trimmed) {
			return true
		}
		if tomlKeyValue.MatchString(trimmed) && !tomlComment.MatchString(l) {
			return true
		}
	}
	return false
}
