package filemap

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/kaushal/skim/internal/digest"
)

var (
	yamlKeyLine    = regexp.MustCompile(`^(\s*)([\w.\-/]+)\s*:`)
	yamlListItem   = regexp.MustCompile(`^\s*-\s+`)
	yamlComment    = regexp.MustCompile(`^\s*#`)
	yamlDocSep     = regexp.MustCompile(`^---`)
	yamlGenerated  = regexp.MustCompile(`@generated|DO NOT EDIT|Code generated|autogenerated`)
)

// yamlSection tracks one top-level key block while parsing.
type yamlSection struct {
	key       string
	indent    int
	startLine int
	endLine   int
	children  []string
	listCount int
}

// parseYAMLFile builds a FileMap from a YAML source file using an
// indent-based line scanner. It extracts top-level keys and their immediate
// children, which is enough to navigate Kubernetes manifests, Docker Compose
// files, GitHub Actions workflows, and most other structured YAML configs.
//
// YAML is not fully parsed (no anchor resolution, no multi-document merging,
// no flow scalars) — the goal is a structural digest, not a YAML interpreter.
func parseYAMLFile(src, filePath string) (digest.FileMap, error) {
	lines := splitLines(src)
	if len(lines) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: empty file")
	}

	if !hasYAMLStructure(lines) {
		return digest.FileMap{}, fmt.Errorf("filemap: no recognizable YAML structure")
	}

	generated := false
	for _, l := range lines[:min(len(lines), 5)] {
		if yamlGenerated.MatchString(l) {
			generated = true
			break
		}
	}

	var topLevel []*yamlSection
	var current *yamlSection

	closeSection := func(endLine int) {
		if current != nil {
			current.endLine = endLine
			topLevel = append(topLevel, current)
			current = nil
		}
	}

	for i, raw := range lines {
		lineNo := i + 1

		// Skip blank lines and comments.
		t := strings.TrimSpace(raw)
		if t == "" || yamlComment.MatchString(raw) {
			continue
		}

		// Multi-document separator resets top-level scanning.
		if yamlDocSep.MatchString(raw) {
			closeSection(lineNo - 1)
			continue
		}

		m := yamlKeyLine.FindStringSubmatch(raw)
		if m == nil {
			// List item or continuation: contribute to current section.
			if current != nil && yamlListItem.MatchString(raw) {
				current.listCount++
			}
			continue
		}

		indent := len(m[1])
		key := m[2]

		if indent == 0 {
			// New top-level key.
			closeSection(lineNo - 1)
			current = &yamlSection{
				key:       key,
				indent:    indent,
				startLine: lineNo,
			}
		} else if indent <= 4 && current != nil {
			// Immediate child of the top-level key (one indent level in).
			// Collect up to 8 child keys to describe the section.
			parentIndent := current.indent
			if indent > parentIndent && len(current.children) < 8 {
				current.children = append(current.children, key)
			}
		}
	}
	closeSection(len(lines))

	if len(topLevel) == 0 {
		return digest.FileMap{}, fmt.Errorf("filemap: no top-level keys found")
	}

	var entries []digest.MapEntry
	var symbols []string

	for _, s := range topLevel {
		if len(symbols) < 40 {
			symbols = append(symbols, s.key)
		}
		kind := yamlKindLabel(s)
		entries = append(entries, digest.MapEntry{
			Lines: lineRange(s.startLine, s.endLine),
			Kind:  kind,
		})
	}

	summary := describeYAMLSummary(symbols, filePath)
	if generated {
		summary += " — generated file, do not edit directly"
	}

	var notes string
	if generated {
		notes = "generated file — edit the generator, not this file"
	}

	return digest.FileMap{
		Summary: summary,
		Map:     entries,
		Symbols: symbols,
		Notes:   notes,
	}, nil
}

// yamlKindLabel builds the map entry kind label from a section's children and
// list count, giving more context than the key name alone.
func yamlKindLabel(s *yamlSection) string {
	if s.listCount > 0 && len(s.children) == 0 {
		return fmt.Sprintf("%s: list[%d]", s.key, s.listCount)
	}
	if len(s.children) > 0 {
		shown := s.children
		if len(shown) > 5 {
			shown = shown[:5]
		}
		label := fmt.Sprintf("%s: {%s}", s.key, strings.Join(shown, ", "))
		if len(s.children) > 5 {
			label += fmt.Sprintf(" (+%d more)", len(s.children)-5)
		}
		return label
	}
	if s.listCount > 0 {
		return fmt.Sprintf("%s: list[%d] with sub-keys", s.key, s.listCount)
	}
	return s.key
}

// describeYAMLSummary infers the file type from its name or top-level keys.
func describeYAMLSummary(keys []string, filePath string) string {
	base := strings.ToLower(filePath)
	if i := strings.LastIndexByte(base, '/'); i >= 0 {
		base = base[i+1:]
	}

	// Well-known filenames.
	switch {
	case base == "docker-compose.yml" || base == "docker-compose.yaml" ||
		base == "compose.yml" || base == "compose.yaml":
		return "Docker Compose service definition"
	case strings.HasSuffix(base, ".github/workflows/") ||
		base == "action.yml" || base == "action.yaml":
		return "GitHub Actions workflow"
	}

	// Well-known key patterns.
	keySet := map[string]bool{}
	for _, k := range keys {
		keySet[k] = true
	}

	switch {
	case keySet["apiVersion"] && keySet["kind"] && keySet["metadata"]:
		// Kubernetes manifest — use kind value if present.
		return "Kubernetes manifest"
	case keySet["services"] && (keySet["version"] || keySet["networks"] || keySet["volumes"]):
		return "Docker Compose service definition"
	case keySet["name"] && keySet["on"] && keySet["jobs"]:
		return "GitHub Actions workflow"
	case keySet["name"] && keySet["version"] && keySet["dependencies"]:
		return "package manifest (YAML)"
	}

	return fmt.Sprintf("YAML document — %d top-level key(s)", len(keys))
}

// hasYAMLStructure returns true when src has at least one key-value line,
// rejecting empty files and plaintext content.
func hasYAMLStructure(lines []string) bool {
	for _, l := range lines {
		if yamlKeyLine.MatchString(l) {
			return true
		}
	}
	return false
}
